README.md
kas-macros/src/args.rs
kas-macros/src/lib.rs
kas-wgpu/examples/calculator.rs
kas-wgpu/examples/clock.rs
kas-wgpu/examples/counter.rs
kas-wgpu/examples/gallery.rs
kas-wgpu/examples/layout.rs
kas-wgpu/examples/stopwatch.rs
kas-wgpu/examples/theme.rs
kas-wgpu/src/theme.rs
src/event/enums.rs
src/event/events.rs
src/event/handler.rs
src/event/manager.rs
src/event/mod.rs
src/event/response.rs
src/macros.rs
src/traits.rs
src/widget/button.rs
src/widget/checkbox.rs
src/widget/dialog.rs
src/widget/scroll.rs
src/widget/text.rs
src/widget/window.rs

Fixes #21
~(currently incomplete, but roughly equivalent to previous functionality)~
Addresses both listed issues.
Notably omitted is "flicking" scrollable regions (momentum & drag model), but ~this is strictly internal to the `ScrollRegion` widget thus can easily land later~ this requires support for "animated" widgets.

Revise event handling

---

kas-wgpu/examples/gallery.rs
kas-wgpu/src/draw/draw_pipe.rs
kas-wgpu/src/draw/round_pipe.rs
kas-wgpu/src/draw/square_pipe.rs
kas-wgpu/src/event.rs
kas-wgpu/src/lib.rs
kas-wgpu/src/window.rs
src/layout/sizer.rs
src/toolkit.rs

Allows window creation from event handlers (see #28).
In my testing on X11 it's somewhat slow with debug builds (faster but still not instantaneous with release builds). ~I cannot measure latency > 1ms within the event loop, so I don't think the problem lies within `kas` / `kas_wgpu`.~
Edit: slow window creation was due to redundant shader compilation.

Dynamic window creation

---

kas-macros/src/args.rs
kas-macros/src/lib.rs
kas-wgpu/examples/clock.rs
kas-wgpu/examples/stopwatch.rs
kas-wgpu/examples/sync-counter.rs
kas-wgpu/src/event_loop.rs
kas-wgpu/src/lib.rs
kas-wgpu/src/shared.rs
kas-wgpu/src/window.rs
src/event/handler.rs
src/event/manager.rs
src/event/mod.rs
src/event/update.rs
src/toolkit.rs
src/traits.rs
src/widget/button.rs

Implements the remainder of #37.
Also some fixes:
- allows generics in `make_widget!` macro
- sets `cur_id` for touch grabs (re-enables highlighting as a side-effect)
- corrects mapping of WidgetId in configure

Implement inter-window update

---

kas-wgpu/examples/gallery.rs
kas-wgpu/src/draw/draw_pipe.rs
kas-wgpu/src/draw/draw_text.rs
kas-wgpu/src/draw/flat_round.rs
kas-wgpu/src/draw/mod.rs
kas-wgpu/src/draw/shaded_round.rs
kas-wgpu/src/draw/shaded_square.rs
kas-wgpu/src/draw/shaders.rs
kas-wgpu/src/draw/shaders/flat_round.frag
kas-wgpu/src/draw/shaders/scaled3122.vert
kas-wgpu/src/theme/dimensions.rs
kas-wgpu/src/theme/flat_theme.rs
kas-wgpu/src/theme/mod.rs
kas-wgpu/src/theme/shaded_theme.rs
src/draw/mod.rs
src/theme/dimensions.rs
src/theme/mod.rs

First, this switches to a higher-level (and more limiting) API in `DrawText`. This is not sufficient for all usages (though nor was the previous); fleshing this out properly can wait until the text-processing work lands (which will be a major step by itself).
Second, this adds several new drawing routines, especially using the `lfat_round` shader, and uses these to significantly improve rendering (navigation-highlights and check-/radio-box marks in both themes, and a few more things in the flat theme).
Third, this moves some of the draw API up to `kas` (core crate). Much of the theme stuff does not need to be in `kas_wgpu`. But much of it also doesn't need to be in `kas`, so perhaps it's time for a `kas-theme` crate (next PR).

Extend draw traits; improve theme rendering

---

Cargo.toml
kas-theme/src/dim.rs
kas-theme/src/flat_theme.rs
kas-theme/src/shaded_theme.rs
kas-wgpu/examples/gallery.rs
kas-wgpu/examples/mandlebrot.rs
kas-wgpu/examples/sync-counter.rs
src/draw/handle.rs
src/geom.rs
src/geom/vector.rs
src/layout/size_rules.rs
src/widget/drag.rs
src/widget/label.rs
src/widget/mod.rs
src/widget/scroll.rs
src/widget/scrollbar.rs
src/widget/slider.rs

- add `DragHandle` abstraction
- add `Slider` widget
- use `Slider` in Mandlebrot example
- allow a label to calculate space via a reservation

Add DragHandle, Slider

---

src/event/manager.rs

Fixes a few little things:
- Enter/Space key presses were consumed by the keyboard-navigation code even when keyboard-navigation was not active
- There was a glitch in the drag offset when moving the cursor off the window
- Highlighting buttons under the cursor during a mouse-grab makes little sense (but currently we still highlight if the mouse button was pressed on a widget which did not initiate a grab, and still process left-clicks normally while the right-button is held down — this may need tweaking)
- Do not bother tracking `Response` values within `handle_winit` since we have no use for them anyway

Input fixes

---

CHANGELOG.md
kas-macros/src/layout.rs
kas-theme/src/col.rs
kas-wgpu/Cargo.toml
kas-wgpu/examples/gallery.rs
kas-wgpu/examples/mandlebrot.rs
kas-wgpu/src/window.rs
src/data.rs
src/draw/handle.rs
src/event/events.rs
src/event/handler.rs
src/event/manager.rs
src/event/mod.rs
src/event/response.rs
src/traits.rs
src/widget/combobox.rs
src/widget/drag.rs
src/widget/frame.rs
src/widget/list.rs
src/widget/menu.rs
src/widget/mod.rs
src/widget/scroll.rs
src/widget/scrollbar.rs
src/widget/slider.rs
src/widget/splitter.rs
src/widget/stack.rs
src/widget/window.rs

Implements a `MenuBar` and sub-menus.
This PR focusses on correct input handling and highlighting of entries, not on graphics. Any widget can be put inside a menu, although it should only receive `Event::Activate` and special `OpenPopup` / `ClosePopup` commands, not direct pointer input.
This does not use appropriate graphics for menus. Although this could be achieved by passing some type of `context` parameter into `Layout::draw` (replacing `disabled: bool`), it should also affect `size_rules`. Special menu widgets may be a better option.

MenuBar, sub-menus, fixes

---

kas-wgpu/examples/mandlebrot.rs
src/event/events.rs
src/event/handler.rs
src/event/manager.rs
src/event/manager/mgr_pub.rs
src/event/manager/mgr_tk.rs
src/event/response.rs
src/widget/scroll.rs
src/widget/stack.rs

This allows ScrollRegion and Mandlebrot to respond to keyboard navigation when a child widget or no widget has navigation focus.
It also ensures visibility of a widget when focussed via Tab.

Key navigation: scroll, visibility

---

kas-wgpu/src/draw/shaders/flat_round.frag
kas-wgpu/src/draw/shaders/shaded_round.frag
kas-wgpu/src/draw/shaders/shaded_square.frag

This causes render problems on Intel Linux and isn't needed.

Remove noperspective specifyer in fragment shaders

---

kas-theme/src/multi.rs
kas-wgpu/examples/calculator.rs
kas-wgpu/examples/custom-theme.rs
kas-wgpu/examples/gallery.rs
kas-wgpu/examples/stopwatch.rs
kas-wgpu/src/shared.rs
kas-wgpu/src/window.rs
src/class.rs
src/data.rs
src/event/manager.rs
src/event/manager/mgr_pub.rs
src/event/manager/mgr_tk.rs
src/event/mod.rs
src/lib.rs
src/prelude.rs
src/string.rs
src/toolkit.rs
src/traits/widget.rs
src/widget/button.rs
src/widget/checkbox.rs
src/widget/combobox.rs
src/widget/dialog.rs
src/widget/label.rs
src/widget/menu/menu_entry.rs
src/widget/menu/submenu.rs
src/widget/mod.rs
src/widget/radiobox.rs

This adjusts how keyboard bindings work:
- bindings can be inferred from labels (e.g. "&File" binds `F`)
- bindings are separated into multiple layers, thus e.g. key-bindings from menu items are only accessible when that menu is open
- bindings are visible and active when Alt is held
- if "alt_bypass" is enabled, bindings are also active without Alt
To do this, `LabelString` and `AccelString` types are introduced (in the new `kas::string` module). These types parse labels with `&` bindings.

Add Alt+Key accelerator keys

---

Cargo.toml
README.md
kas-macros/Cargo.toml
kas-macros/README.md
kas-macros/build.rs
kas-macros/src/args.rs
kas-macros/src/lib.rs
kas-theme/Cargo.toml
kas-theme/src/lib.rs
kas-theme/src/multi.rs
kas-theme/src/theme_dst.rs
kas-wgpu/Cargo.toml
kas-wgpu/README.md
kas-wgpu/examples/mandlebrot.rs

It turns out compatibility with stable Rust is significantly easier than last time I evaluated this.
The `make_widget!` macro remains nightly-only, but is now strictly a convenience macro, thus can be avoided. Most examples will continue to use it (since it is the intended way to write GUIs), but some examples will be kept compatible with stable Rust.
The `clock`, `hello` and `mandlebrot` examples are now compatible with stable Rust.
Specifically:
- proc_macro diagnostics are auto-enabled on nightly compilers
- an `unsize` feature flag was added to `kas-theme` (and forwarded in `kas-wgpu`)
- the Mandlebrot example was adjusted to avoid `make_widget!`

Stable rust compatibility

---

Cargo.toml
kas-theme/src/dim.rs
kas-wgpu/examples/layout.rs
src/event/manager.rs
src/event/manager/mgr_tk.rs
src/prelude.rs
src/toolkit.rs
src/traits/widget.rs
src/widget/mod.rs
src/widget/slider.rs

This includes breaking changes, so probably there won't be another 0.4.x release.
The `Slider`'s value type bounds changed to support `std::time::Duration`.
We also pull in a change from the `view` branch: protection against getting stuck in a loop due to sending `TkAction::Reconfigure` from `WidgetConfig::configure`.

Misc changes [breaking]

---

Cargo.toml
kas-theme/src/dim.rs
kas-theme/src/flat_theme.rs
kas-theme/src/font.rs
kas-theme/src/shaded_theme.rs
kas-wgpu/Cargo.toml
kas-wgpu/examples/clock.rs
kas-wgpu/examples/mandlebrot.rs
kas-wgpu/src/draw/draw_text.rs
kas-wgpu/src/draw/mod.rs
src/draw/handle.rs
src/draw/mod.rs
src/draw/text.rs
src/event/events.rs
src/event/manager.rs
src/event/manager/mgr_pub.rs
src/event/manager/mgr_tk.rs
src/event/response.rs
src/geom/vector.rs
src/widget/combobox.rs
src/widget/editbox.rs
src/widget/menu/menubar.rs
src/widget/menu/submenu.rs
src/widget/scroll.rs
src/widget/slider.rs

This PR updates to `glyph_brush` 0.7, which allows reliably translating a string index to a glyph position (https://github.com/alexheretic/glyph-brush/issues/80).
- draw a real edit position marker
The PR adds a dependency on [unicode-segmentation](https://github.com/unicode-rs/unicode-segmentation), allowing the edit cursor to advance by a grapheme clustor.
Finally, it renames `NavKey` → `ControlKey`, extends it, avoids sending this simultaneously with `ReceivedCharacter`, and sends `ControlKey` with char focus.
- `EditBox` can respond to nav keys to move the edit marker
This is part of #13, but still has a lot missing (mouse-position to string index, text selection, multi-line editing).

Update glyph_brush, movable edit marker

---

CHANGELOG.md
ROADMAP.md
kas-theme/src/dim.rs
kas-theme/src/flat_theme.rs
kas-theme/src/shaded_theme.rs
kas-wgpu/examples/layout.rs
kas-wgpu/src/draw/draw_text.rs
kas-wgpu/src/window.rs
src/draw/handle.rs
src/draw/text.rs
src/event/manager/mgr_pub.rs
src/geom/vector.rs
src/toolkit.rs
src/traits.rs
src/traits/impls.rs
src/traits/widget.rs
src/widget/dialog.rs
src/widget/editbox.rs
src/widget/menu.rs
src/widget/window.rs

This PR allows look-up of the text index nearest the mouse cursor. It doesn't work that well for multi-line text, but external line splitting is probably the best approach here so this is not solved for now.
Also, add a roadmap.

Roadmap, text_index_nearest

---

kas-theme/src/flat_theme.rs
kas-theme/src/shaded_theme.rs
kas-wgpu/src/window.rs
src/draw/text.rs
src/event/events.rs
src/event/manager.rs
src/event/manager/mgr_pub.rs
src/event/manager/mgr_tk.rs
src/widget/editbox.rs

Some minor stuff:
- Force minimum window size of 1x1 since 0-sized windows crashes (on X11)
- Allow `ShadedTheme` to re-use code from `FlatTheme`
- Add detection for double-click, triple-click etc. (currently unused)

Detect double-click; theme code reuse

---

Cargo.toml
kas-theme/src/multi.rs
kas-wgpu/examples/calculator.rs
kas-wgpu/examples/dynamic.rs
kas-wgpu/examples/gallery.rs
kas-wgpu/src/draw/draw_text.rs
kas-wgpu/src/shared.rs
kas-wgpu/src/window.rs
src/class.rs
src/draw/handle.rs
src/event/manager/mgr_pub.rs
src/event/mod.rs
src/geom.rs
src/geom/vector.rs
src/prelude.rs
src/string.rs
src/text.rs
src/toolkit.rs
src/widget/button.rs
src/widget/combobox.rs
src/widget/dialog.rs
src/widget/editbox.rs
src/widget/frame.rs
src/widget/label.rs
src/widget/menu/menu_entry.rs
src/widget/menu/menu_frame.rs
src/widget/menu/submenu.rs
src/widget/window.rs

From the commit removing `CowString`:
> This is a mis-placed optimisation: the only place it helps is with string literals; real apps mostly won't use these anyway due to translation support.

Update kas-text, remove CowString

---

Cargo.toml
kas-macros/src/args.rs
kas-theme/src/flat_theme.rs
kas-wgpu/examples/clock.rs
kas-wgpu/examples/layout.rs
kas-wgpu/src/draw/draw_text.rs
src/data.rs
src/draw/handle.rs
src/macros.rs
src/text.rs
src/widget/button.rs
src/widget/combobox.rs
src/widget/editbox.rs
src/widget/label.rs
src/widget/menu/menu_entry.rs
src/widget/menu/submenu.rs

This gets us back to feature parity with the situation prior to kas-text, plus has correct multi-line highlighting.
Corresponding PR: https://github.com/kas-gui/kas-text/pull/5

kas-text: use re-implemented breaking and shaping

---

Cargo.toml
kas-theme/src/dim.rs
kas-theme/src/flat_theme.rs
kas-theme/src/shaded_theme.rs
kas-wgpu/examples/layout.rs
src/text.rs
src/widget/editbox.rs

Multi-line text editing now works fairly well, even with bidirectional content!
There are still several major limitations:
-   the design doesn't scale to large documents (noticeable when editing a couple hundred lines)
-   there is no implicit support for scrolling when texts don't fit in the edit box
-   short-cuts aren't handled aside from a few already mapped to control-codes by the OS (so e.g. Ctrl+V works on KDE/Linux but not Ctrl+A)
-   the undo buffer is limited to a single action and handled directly by `EditBox`
-   text formatting / highlighting (other than background) isn't started yet

Update kas-text (navigation)

---

Cargo.toml
kas-theme/src/dim.rs
kas-theme/src/flat_theme.rs
kas-theme/src/shaded_theme.rs
kas-wgpu/examples/clock.rs
kas-wgpu/src/draw/draw_text.rs
src/draw/handle.rs
src/draw/mod.rs
src/event/events.rs
src/geom/vector.rs
src/prelude.rs
src/text.rs
src/widget/button.rs
src/widget/combobox.rs
src/widget/editbox.rs
src/widget/label.rs
src/widget/menu/menu_entry.rs
src/widget/menu/submenu.rs

This has some API adjustments, but most notably EditBox now supports scrolling its contents:
- by ctrl+mouse drag
- by touch drag (or move cursor after 1sec delay / touch without drag)
- mouse wheel (needs speed adjustment, but possibly elsewhere)

Allow scrolling editable text; remove PreparedText wrapper

---

Cargo.toml
kas-theme/src/flat_theme.rs
src/widget/editbox.rs

This implements support for double- and triple-click selection (word and line), including drag mode.
When multiple edit cursors are displayed, the secondary one is shown in grey (piggy-backing the `button_disabled` colour for now).
We also update to the first release version of kas-text.

Double/triple click selection, kas-text 0.1

---

kas-wgpu/examples/mandlebrot.rs
src/event/events.rs
src/event/manager.rs
src/event/manager/mgr_pub.rs
src/widget/editbox.rs

The middle commit is inspired by https://github.com/linebender/druid/issues/1124. We take the lazy option and deselect on any loss of input focus which is what a number of UI controls do. (If we instead want to only clear on another selection starting, I guess we should add a method like `Manager::report_selection(&mut self, id: WidgetId)`, and send `Deselect` to the last such widget.)

Deselect via scroll and focus loss; fix scrolling

---

kas-theme/src/flat_theme.rs
src/widget/editbox.rs

The allocation was in fact missing (bug) despite explicit consideration in scroll logic. Instead we do the simple thing and allow the marker to be drawn in the margin. This fixes the hidden edit cursor at the start of RTL text.

Remove EditBox's explicit allocation for edit marker

---

Cargo.toml
kas-theme/src/flat_theme.rs
kas-theme/src/shaded_theme.rs
kas-wgpu/examples/clock.rs
kas-wgpu/examples/markdown.rs
kas-wgpu/src/draw/draw_text.rs
src/draw/handle.rs
src/draw/mod.rs
src/event/manager/mgr_pub.rs
src/text/string.rs
src/traits/widget.rs
src/widget/editbox.rs
src/widget/label.rs

The `WidgetChildren::find` and `find_mut` methods now use binary search to achieve `O(log n)` performance over large numbers of children. This is only really relevant on *large* lists of children and still probably not the most significant cost, but is another step towards #91.
Other changes depend on these changes: https://github.com/kas-gui/kas-text/pull/34
`EditBox` now enters `\t` on the Tab key to allow testing the new tab support. (Should be configurable later, or depend on the use case?)
Added `DrawHandle::text_effects` and revised `DrawText` methods. We can now forward effects like strikethrough from parsed text. We keep `DrawHandle::text_accel` (since behaviour depends on an extra state parameter), but move the effect-list creation up to `AccelString`.

O(log n) find, DrawHandle::text_effects, tab entry

---

kas-wgpu/examples/mandlebrot.rs
src/draw/handle.rs
src/layout/grid_solver.rs
src/layout/size_rules.rs
src/widget/drag.rs
src/widget/slider.rs

"Fixes" space distribution within grid spans (well, one bug fix + one improvement; this isn't perfection).
Fixes size of a slider handle when the slider's thickness is larger than required. Graphics are still poor in this case.
The Mandlebrot example now occupies the right margin with its main widget.

Span distributions and Mandlebrot

---

kas-theme/src/dim.rs
kas-wgpu/examples/markdown.rs
src/draw/handle.rs
src/event/events.rs
src/event/manager.rs
src/event/manager/mgr_pub.rs
src/event/manager/mgr_tk.rs
src/text.rs
src/text/selection.rs
src/traits/widget.rs
src/widget/editbox.rs

New `LostSelFocus` event: widgets may now keep a selection when losing nav focus, but this event is fired when a new widget supporting selection receives focus to prevent multiple selections.
New `SelectionHelper` struct to abstract out some of the selection logic in `EditBox`. This abstraction is chiefly for #138 (which may not land), but may as well be merged.

Fixes for selection and ScrollRegion<Label>

---

Cargo.toml
kas-theme/src/dim.rs
kas-theme/src/flat_theme.rs
kas-theme/src/shaded_theme.rs
kas-wgpu/examples/calculator.rs
kas-wgpu/examples/clock.rs
kas-wgpu/examples/counter.rs
kas-wgpu/examples/custom-theme.rs
kas-wgpu/examples/dynamic.rs
kas-wgpu/examples/hello.rs
kas-wgpu/examples/layout.rs
kas-wgpu/examples/mandlebrot.rs
kas-wgpu/examples/markdown.rs
kas-wgpu/examples/splitter.rs
kas-wgpu/examples/stopwatch.rs
kas-wgpu/examples/sync-counter.rs
kas-wgpu/src/lib.rs
src/traits.rs

A direct effect of the introduction of MarkdownError in kas-text is that our markdown example can now display errors in the app (without contextual information, but considering the errors are only due to unsupported features this likely isn't a big deal).

Builder-style methods for Theme and Toolkit; kas-text update

---

Cargo.toml
src/event/manager.rs
src/event/manager/mgr_pub.rs
src/event/manager/mgr_tk.rs

Add `linear-map` dependency and use for a couple of fields in the event manager (cleaner code). Somehow I missed this lib before.
During reconfigure, attempt to map `WidgetId` data within `time_updates`, `handle_updates` and `pending` fields of `ManagerState`. Previously these fields were cleared, which could cause a few subtle bugs (e.g. cancelling notification of a `Window::on_drop` future).

Use LinearMap, clear less state in reconfigure

---

Cargo.toml
README.md
kas-wgpu/README.md
kas-wgpu/src/lib.rs
kas-wgpu/src/options.rs
kas-wgpu/src/window.rs
src/draw/handle.rs
src/draw/mod.rs
src/event/manager.rs
src/event/manager/mgr_pub.rs
src/event/manager/mgr_shell.rs
src/lib.rs
src/prelude.rs
src/toolkit.rs

Previously, our usage of the word 'toolkit' was in some instances non-standard. This PR uses 'shell' instead, matching the usage in other toolkits such as Druid and Iced.
The word `Toolkit` is retained where appropriate, e.g. the `Toolkit` type provided by the `kas-wgpu` shell. (Here it may also be surprising that the toolkit type is provided by the shell, but the name is appropriate to this usage. Although it seems appropriate to move this type to `kas` this would require another abstraction trait and there is very little reason to do so in practice, thus we [Keep It Simple, Stupid!](https://en.wikipedia.org/wiki/KISS_principle))

Terminology: replace 'toolkit' with 'shell' where appropriate

---

kas-macros/src/layout.rs
kas-wgpu/examples/filter-list.rs
kas-wgpu/examples/gallery.rs
kas-wgpu/examples/markdown.rs
kas-wgpu/examples/sync-counter.rs
src/event/manager/mgr_pub.rs
src/event/update.rs
src/widget/editbox.rs
src/widget/mod.rs
src/widget/view/list.rs
src/widget/view/mod.rs
src/widget/view/shared.rs
src/widget/view/single.rs

This `Accessor` and `ViewWidget` framework is supposed to be KAS's answer for widgets which do not own or directly access their data (shared and filtered data).
This design takes a little inspiration from Druid's lens system, but ultimately works quite differently since KAS widgets have *many* more methods than Druid widgets (thus directly passing data everywhere is quite impractical), and our existing design (storing data in widgets) already works well for many cases (constant and unshared data).
Status
- implemented for single (unindexed) data, making the sync-counter significantly simpler for the same functionality
- very early work for list data
- *hopefully* the design will extend nicely to deal with `Vec<T>` (where length is not constant) and to multi-dimensional types

Introduce view widgets

---

kas-macros/src/layout.rs
kas-wgpu/Cargo.toml
kas-wgpu/examples/dynamic.rs
kas-wgpu/examples/filter-list.rs
kas-wgpu/examples/gallery.rs
kas-wgpu/examples/markdown.rs
src/draw/handle.rs
src/widget/mod.rs
src/widget/scroll.rs
src/widget/scrollbar.rs
src/widget/view/list.rs

Tested with 31567568 entries (much more than that and the `u32` type used for pixel sizes becomes a problem).
Also fix (or work around) https://github.com/rust-lang/rust/issues/78113

ScrollBars wrapper, filter-list with large numbers of entries

---

.github/workflows/test.yml
Cargo.toml
README.md
kas-wgpu/Cargo.toml
kas-wgpu/examples/filter-list.rs
kas-wgpu/src/lib.rs
kas-wgpu/src/options.rs
kas-wgpu/src/shared.rs
kas-wgpu/src/window.rs
src/conv.rs
src/dir.rs
src/draw/colour.rs
src/event/config.rs
src/event/enums.rs
src/event/events.rs
src/event/manager.rs
src/event/manager/mgr_shell.rs
src/event/mod.rs
src/event/shortcuts.rs
src/geom.rs
src/geom/vector.rs

Adds working read & write support for shortcut configuration.
JSON and YAML support are included. TOML is not because the `toml` crate does not support enums as map keys and I don't see another TOML+Serde crate.
Adjusts `kas_wgpu::Options`, adding two env vars controlling behaviour.
Some cleanup is needed before merge, but otherwise I think this is good for now. The file format is unstable and until that changes, there won't be a default config path, though later there should be (using the `directories` crate or similar).
~~TODO: cleanup commits, better documentation?~~
Edit: done cleanup; serde is now optional.

Config read/write support

---

README.md
kas-theme/src/col.rs
kas-theme/src/dim.rs
kas-wgpu/examples/dynamic.rs
kas-wgpu/examples/gallery.rs
src/dir.rs
src/draw/handle.rs
src/geom.rs
src/layout/align.rs
src/layout/grid_solver.rs
src/layout/mod.rs
src/layout/row_solver.rs
src/layout/size_rules.rs
src/layout/sizer.rs
src/widget/checkbox.rs
src/widget/editbox.rs
src/widget/menu/menu_entry.rs
src/widget/menu/submenu.rs
src/widget/mod.rs
src/widget/radiobox.rs
src/widget/stack.rs

`EditBox` is now a wrapper around `EditField`, which inherited most of the old `EditBox`'s logic. `EditField` can be used directly (without borders or background).
Some changes to alignment and stretch policies (see commits).
Readme update.

EditField, README, tweak alignment

---

kas-theme/src/dim.rs
kas-theme/src/flat_theme.rs
kas-theme/src/shaded_theme.rs
src/draw/handle.rs
src/layout/mod.rs
src/layout/size_rules.rs
src/layout/size_types.rs
src/widget/button.rs
src/widget/combobox.rs
src/widget/editbox.rs
src/widget/frame.rs
src/widget/menu/menu_entry.rs
src/widget/menu/menu_frame.rs
src/widget/menu/submenu.rs
src/widget/separator.rs
src/widget/splitter.rs

Adds a `FrameRules` type as a special variant of `SizeRules`.
Some fixes and tweaks around margins, and new `text_margin` (between `inner_margin` and `outer_margin`).

Margins, FrameRules

---

kas-theme/src/flat_theme.rs
kas-theme/src/shaded_theme.rs
src/draw/handle.rs
src/event/manager/mgr_pub.rs
src/geom.rs
src/geom/vector.rs
src/layout/size_rules.rs
src/prelude.rs
src/widget/button.rs
src/widget/combobox.rs
src/widget/editbox.rs
src/widget/frame.rs
src/widget/menu/menu_entry.rs
src/widget/menu/menu_frame.rs
src/widget/menu/submenu.rs
src/widget/scroll.rs
src/widget/scrollbar.rs
src/widget/view/list.rs

ViewList now supports item selection via click (toggle on click). This is a little basic and doesn't support things like range-selection or a "select-all" command and has a simple backing type, thus probably needs extending later.
Scroll-region margins saw some revision: contents are now surrounded by a margin correctly, while keeping the margin within the drawable scroll-region.
`Size`, `Coord` and `Offset` now have a `set_component` method, simplifying several `size_rules` impls.

ViewList selection, set_component, scroll-region margins

---

kas-wgpu/examples/filter-list.rs
src/widget/view/list.rs
src/widget/view/mod.rs

Allows single/multiple or no selection with `ViewList`, which should be enough for the 7GUIs CRUD example app ...
... except that selection identifiers are dependent on the filter. Solving this requires significant changes to the `Accessor` trait.
Further, the `Accessor` trait needs some tweaks for write support (e.g. for cell editing within a spreadsheet).

ViewList: multiple selection modes

---

kas-macros/src/args.rs
kas-macros/src/layout.rs
kas-wgpu/examples/README.md
kas-wgpu/examples/async-event.rs
kas-wgpu/examples/calculator.rs
kas-wgpu/examples/cursors.rs
kas-wgpu/examples/layout.rs
kas-wgpu/examples/mandlebrot.rs
src/event/manager.rs
src/event/manager/mgr_pub.rs
src/event/manager/mgr_shell.rs
src/event/response.rs
src/layout/size_rules.rs
src/traits/impls.rs
src/traits/widget.rs
src/widget/menu.rs
src/widget/menu/menubar.rs
src/widget/window.rs

This adds two examples (heavily inspired by Druid's examples), plus a few small changes:
- `WidgetChildren::find_child` was renamed to `find_leaf` since it finds the leaf-most descendant; a new `find_child` method was added, returning the index of the child which is an ancestor of the given id
- Setting a hover cursor icon for a widget now applies transitively to descendants, where those descendants' icons are `Default`. This simplifies the new example but it isn't clear if this is the right choice (or if `cursor_icon` should return `Option<CursorIcon>` so that children can force the default icon). It may be necessary to revisit this later.
- `SizeRules` has two new constructors to ease use with virtual pixels ~~(though given that these are purely convenience wrappers, possibly they …

Examples: async-event, cursor gallery

---

kas-theme/src/dim.rs
kas-wgpu/examples/clock.rs
kas-wgpu/examples/dynamic-view.rs
kas-wgpu/examples/mandlebrot.rs
kas-wgpu/examples/splitter.rs
src/data.rs
src/layout/align.rs
src/layout/grid_solver.rs
src/layout/mod.rs
src/layout/size_rules.rs
src/layout/size_types.rs
src/prelude.rs
src/widget/filler.rs
src/widget/progress.rs
src/widget/scrollbar.rs
src/widget/slider.rs
src/widget/view/filter.rs
src/widget/view/list_view.rs
src/widget/view/shared_data.rs

The `StretchPolicy` type was revised, mostly to make clear that what was `StretchPolicy::Fixed` does not actually fix the size. Text types no longer use `Filler` policy (except buttons horizontally) since this may have unintended consequences.
`FilteredList` now applies the filter to all methods, not just to iteration. `ListData` has an extra method.
`ListView` will now deselect data which is no longer visible.

Revise StretchPolicy → Stretch; shared data fixes + ListData::contrains_key

---

kas-wgpu/examples/data-list-view.rs
src/core/widget.rs
src/event/components.rs
src/event/manager/mgr_pub.rs
src/widget/combobox.rs
src/widget/editbox.rs
src/widget/list.rs
src/widget/menu/submenu.rs
src/widget/view/list_view.rs
src/widget/view/matrix_view.rs
src/widget/view/single_view.rs

`EditGuard` now has a `focus_gained` method, allowing custom actions on gaining text-input focus.
Replace `Layout::spatial_range` with `spatial_nav`, fixing iteration order for elements in `ListView` and `MatrixView` (but not changing the odd behaviour that sometimes tab scrolls to new elements and sometimes it doesn't).
Implement arrow-key and page up/down, home and end key navigation for `ListView` and for `MatrixView` where the immediate widget supports key-navigation.

Arrow and tab navigation for views; EditGuard::focus_gained

---

CHANGELOG.md
Cargo.toml
kas-macros/Cargo.toml
kas-theme/Cargo.toml
kas-wgpu/Cargo.toml
src/widget/list.rs
src/widget/view/matrix_view.rs

It's ready.
The major focus of this release is "view widgets": the ability to construct a
synchronised view over shared data.
The new view widgets allow completion of the "CRUD" (Create, Read, Update,
Delete) [7GUIs challenge app](https://github.com/kas-gui/7guis/). The use of
view widgets allows data-UI separation and scaling to larger data sets (mainly
limited by the `O(n)` filter in this example). Work also started on the Cells
challenge (mini-spreadsheet), though many details of the app and of the
`MatrixView` widget still need addressing, especially drawing, multi-cell
selection and keyboard handling.
Additionally, this version saw development of a new mini-library, `kas::conv`,
which spun off into its own lib [easy-cast](https://crates.io/crates/easy-cast).
[Read the full CHANGELOG …

Release v0.7

---

kas-theme/src/flat_theme.rs
kas-theme/src/multi.rs
kas-theme/src/shaded_theme.rs
kas-theme/src/theme_dst.rs
kas-theme/src/traits.rs
kas-wgpu/examples/custom-theme.rs
kas-wgpu/src/draw/draw_pipe.rs
kas-wgpu/src/draw/flat_round.rs
kas-wgpu/src/draw/shaded_square.rs
kas-wgpu/src/window.rs
src/draw/colour.rs
src/draw/handle.rs
src/draw/mod.rs
src/geom.rs
src/widget/combobox.rs
src/widget/menu.rs
src/widget/menu/submenu.rs
src/widget/mod.rs
src/widget/window.rs

Switching to our own glyph caching/drawing system fixed the clipping problems with overlays. This PR fixes clipping for embedded scroll regions and adds transparent shadows around popup menus (shaded theme only).
The `MenuFrame` widget is removed (no longer needed).
There are also a few small improvements to drawing code, plus some tweaks to rounded frame thickness.

Overlay borders / shadows

---

.github/workflows/test.yml
Cargo.toml
README.md
example-config/theme.yaml
kas-theme/src/config.rs
kas-theme/src/dim.rs
kas-theme/src/flat_theme.rs
kas-theme/src/shaded_theme.rs
kas-theme/src/traits.rs
kas-wgpu/Cargo.toml
kas-wgpu/src/draw/text_pipe.rs
kas-wgpu/src/options.rs
src/text.rs

Mostly this concerns work done in `kas-text`:
- https://github.com/kas-gui/kas-text/pull/47
- https://github.com/kas-gui/kas-text/pull/48
Font resolution has been completely updated and no longer uses `font-kit` as a dependency. It is now configurable via aliases (see config example). Rustybuzz is supported and used by default for shaping; Harfbuzz and no shaping are still options.

Use rustybuzz for shaping and enable by default; allow custom font aliases

---

Cargo.toml
example-config/theme.yaml
kas-theme/Cargo.toml
kas-theme/src/colors.rs
kas-theme/src/config.rs
kas-theme/src/dim.rs
kas-theme/src/flat_theme.rs
kas-theme/src/multi.rs
kas-theme/src/shaded_theme.rs
kas-theme/src/theme_dst.rs
kas-theme/src/traits.rs
kas-wgpu/examples/custom-theme.rs
kas-wgpu/src/options.rs
kas-wgpu/src/window.rs
src/draw/handle.rs
src/widget/menu/menu_entry.rs
src/widget/menu/submenu.rs

By default, we now use serif fonts for edit boxes. The example config file uses bold fonts for menus (excepting checkbox entries, which currently use the wrong text class).

Make fonts configurable per text class

---

.github/workflows/test.yml
Cargo.toml
example-config/theme.yaml
kas-theme/src/config.rs
kas-theme/src/flat_theme.rs
kas-theme/src/lib.rs
kas-theme/src/traits.rs
kas-wgpu/Cargo.toml
kas-wgpu/README.md
kas-wgpu/src/draw/draw_pipe.rs
kas-wgpu/src/draw/text_pipe.rs
kas-wgpu/src/shared.rs

Several improvments to text rendering, plus font raster configuration (under theme configuration).
Enables usage of the https://github.com/mooman219/fontdue rasterizer. Subjectively it may be a little better but still isn't perfect and noticably slows down start-up time.
Another option is to align to the horizontal side bearing using `ab_glyph`. In some ways this is better than sub-pixel alignment, in some ways not. Either way it's not close to [grid fitting](https://docs.microsoft.com/en-us/typography/opentype/spec/ttch01#grid-fitting-a-glyph-outline).
The biggest improvement to rendering was one of the simplest changes: vertically aligning text lines to the pixel grid during layout (in `kas-text`). This is enabled by default; other options (including sub-pixel positioning) are now …

Fontdue rasterizer and other font adjustments

---

CHANGELOG.md
Cargo.toml
README.md
ROADMAP.md
kas-macros/Cargo.toml
kas-theme/Cargo.toml
kas-wgpu/Cargo.toml
kas-wgpu/examples/mandlebrot.rs
kas-wgpu/src/draw/images.rs

Updates the CHANGELOG, README and ROADMAP for this release.
Also fixes the mandlebrot example.
No new screenshots/clips because I'm lazy and the only obvious change is the addition of a couple of images.

Prepare 0.8 release; doc

---

Cargo.toml
kas-theme/src/dim.rs
kas-theme/src/flat_theme.rs
kas-theme/src/multi.rs
kas-theme/src/shaded_theme.rs
kas-theme/src/theme_dst.rs
kas-theme/src/traits.rs
kas-wgpu/Cargo.toml
kas-wgpu/examples/custom-theme.rs
kas-wgpu/src/draw/atlases.rs
kas-wgpu/src/draw/draw_pipe.rs
kas-wgpu/src/draw/images.rs
kas-wgpu/src/draw/mod.rs
kas-wgpu/src/draw/text_pipe.rs
kas-wgpu/src/options.rs
kas-wgpu/src/shared.rs
kas-wgpu/src/window.rs
src/draw/handle.rs
src/draw/images.rs
src/draw/mod.rs
src/geom.rs
src/widget/image.rs
src/widget/mod.rs

The API around the shared parts of the draw machinery now looks significantly different:
- `wgpu::{Device, Queue}` handles were moved into `DrawPipe`, allowing referencing within its API
- Image loading was split into *allocate* and *upload* steps
- Image upload is now immediate, avoiding the need to store the (or another) buffer within the draw pipe
- The `DrawShared` trait was renamed `DrawableShared` and hidden from public docs
- A new `DrawShared` struct was introduced as a wrapper around `DrawableShared`, allowing different API
- Image loading code was moved to `kas::draw::images::Images`, adding `Images` as a field to `DrawShared`
Rationales:
- Image loading code may now be shared with other potential toolkit backends
- We can offer users of the draw machinery a nice API (image from …

Revise shared parts of draw pipe; move image loading up to KAS

---

kas-theme/src/flat_theme.rs
kas-theme/src/multi.rs
kas-theme/src/shaded_theme.rs
kas-theme/src/theme_dst.rs
kas-theme/src/traits.rs
kas-wgpu/Cargo.toml
kas-wgpu/examples/async-event.rs
kas-wgpu/examples/clock.rs
kas-wgpu/examples/custom-theme.rs
kas-wgpu/examples/mandlebrot.rs
kas-wgpu/src/draw/draw_pipe.rs
kas-wgpu/src/window.rs
src/draw/draw.rs
src/draw/draw_shared.rs
src/draw/handle.rs
src/draw/mod.rs

This makes the "medium level" draw interface a little easier to use: the `pass` number is now bundled with the `draw` reference.
We could also bundle the `offset` parameter (thus making `DrawHandle::draw_device` easier to use); I opted not to do this since it would require applying the offset multiple times (as an `f32` value on each draw methods' parameters) instead of once (as an integer) in each `DrawHandle` method.
This PR includes some doc revision to the draw module and some minor code refactoring.

Drawable trait and Draw wrapper; casts; documentation

---

kas-theme/src/dim.rs
kas-theme/src/flat_theme.rs
kas-theme/src/shaded_theme.rs
src/draw/draw_shared.rs
src/draw/handle.rs
src/draw/mod.rs
src/event/manager/mgr_pub.rs
src/prelude.rs
src/widget/image.rs

Following #206, this abstracts over a `DrawShared<DS>` object allowing usage where `DS = dyn Drawable`.
Adds `SizeHandle::draw_shared`, replacing image management methods.

DrawSharedT trait

---

kas-macros/src/args.rs
kas-macros/src/lib.rs
kas-wgpu/examples/data-list.rs
kas-wgpu/examples/gallery.rs
kas-wgpu/examples/markdown.rs
src/macros.rs
src/widget/checkbox.rs
src/widget/frame.rs
src/widget/nav_frame.rs
src/widget/radiobox.rs
src/widget/scroll.rs
src/widget/scrollbar.rs

This can now derive for wrapper structs over an internal field, and derive class traits as well as `Deref`. I hope it's not too confusing.

Extend derive(Widget) macro

---

Cargo.toml
kas-wgpu/Cargo.toml
kas-wgpu/examples/canvas.rs
kas-wgpu/src/draw/text_pipe.rs
src/widget/canvas.rs
src/widget/mod.rs
src/widget/svg.rs

This is built over the [tiny-skia API](https://docs.rs/tiny-skia) (which is already used by the `Svg` widget).
The canvas has a built-in cache since it is rendered on the CPU then uploaded as a GPU texture.
Potentially we could add other canvas widgets over other draw APIs in the future, in which case this widget should be renamed.
Note there is already another option for drawing: constructing a new widget with code in the `Layout::draw` implementation (not cached); see e.g. `clock` or `mandlebrot` examples.
Also: some optimisations to text drawing.

Add canvas widget

---

kas-theme/src/draw_shaded.rs
kas-theme/src/flat_theme.rs
kas-theme/src/lib.rs
kas-theme/src/multi.rs
kas-theme/src/shaded_theme.rs
kas-theme/src/theme_dst.rs
kas-theme/src/traits.rs
kas-wgpu/examples/async-event.rs
kas-wgpu/examples/clock.rs
kas-wgpu/examples/custom-theme.rs
kas-wgpu/examples/mandlebrot.rs
kas-wgpu/src/draw/draw_pipe.rs
kas-wgpu/src/options.rs
kas-wgpu/src/shared.rs
kas-wgpu/src/window.rs
src/draw/draw.rs
src/draw/draw_rounded.rs
src/draw/draw_shared.rs
src/draw/handle.rs
src/draw/images.rs
src/draw/mod.rs
src/event/manager/mgr_pub.rs
src/prelude.rs
src/toolkit.rs
src/widget/canvas.rs
src/widget/sprite.rs
src/widget/svg.rs

This is the second part of #223, revisions to the draw API. Most of this PR concerns renaming methods and removing redundant methods, except for the first and third commits which include a reference to shared draw state within `Draw` (later renamed to `DrawIface`), providing users a much simpler API.

Further revisions to draw API

---

kas-theme/src/draw_shaded.rs
kas-theme/src/lib.rs
kas-wgpu/examples/gallery.rs
kas-wgpu/src/draw/custom.rs
kas-wgpu/src/draw/images.rs
kas-wgpu/src/draw/shaded_round.rs
kas-wgpu/src/lib.rs
kas-wgpu/src/options.rs
kas-wgpu/src/window.rs
src/core/data.rs
src/draw/draw_shared.rs
src/draw/images.rs
src/lib.rs
src/widget/dialog.rs
src/widget/window.rs

The gallery now demonstrates a window icon. Closes #44.

Window icons; some docs

---

CHANGELOG.md
Cargo.toml
README.md
kas-macros/Cargo.toml
kas-macros/src/lib.rs

Some recently added logging inadvertently required users to depend on the `log` crate. This PR makes that behaviour opt-in.

Add kas/macros_log feature; prepare 0.9.1

---

.github/workflows/build.yml
crates/kas-core/src/core/widget.rs
crates/kas-core/src/event/config.rs
crates/kas-core/src/event/events.rs
crates/kas-core/src/event/handler.rs
crates/kas-core/src/event/manager.rs
crates/kas-core/src/event/manager/mgr_pub.rs
crates/kas-core/src/event/manager/mgr_shell.rs
crates/kas-core/src/event/shortcuts.rs
crates/kas-widgets/src/combobox.rs
crates/kas-widgets/src/editbox.rs
crates/kas-widgets/src/menu/menubar.rs
crates/kas-widgets/src/menu/submenu.rs
crates/kas-widgets/src/scroll_label.rs
crates/kas-widgets/src/view/list_view.rs
crates/kas-widgets/src/view/matrix_view.rs

Fixes most of #231 plus a few more things:
- Escape does not clear nav focus
- (Shift+)Tab navigates from widgets with char focus (i.e. edit box)
- Key event sending now tries multiple paths until one does *not* return `Response::Unhandled`: (1) the widget with char focus or nav focus
- Allows limited commands (deselect, copy) to be sent to a `ScrollLabel` with selection focus
- Set (keyboard) navigation focus on mouse click or touch (configurable)
- Allow widgets like `EditBox` to request char focus on nav focus
- Make `next_nav_focus` wrap after first/last available widget
- Fix closing pop-ups with <kbd>Esc</kbd>
- `EditGuard::focus_gained` can no longer send a message (breaking change)
- Remove `read_only` state of `Manager`, used while sending pending events (this potentially allows …

Improve keyboard navigation

---

.github/workflows/build.yml
crates/kas-core/src/event/manager.rs
crates/kas-core/src/event/manager/mgr_pub.rs
crates/kas-core/src/event/manager/mgr_shell.rs
crates/kas-theme/src/colors.rs
crates/kas-widgets/src/menu/menubar.rs
crates/kas-widgets/src/menu/submenu.rs

Fixes the remainder of #231:
- Top-level menus are not reachable with the Tab key, only with mouse/touch or Alt+label
- Restore nav focus after closing menus
- Clear character focus (e.g. `EditBox`) when opening a popup menu

Fixes for menus and keyboard navigation

---

.github/workflows/build.yml
crates/kas-core/src/event/manager/mgr_shell.rs
crates/kas-widgets/src/editbox.rs
crates/kas-widgets/src/menu/menubar.rs
crates/kas-widgets/src/scroll_label.rs

Regarding #231:
- clicking on a non-nav widget does not clear or set nav focus
- mouse motion over the base menu bar does not do anything
- remove a couple of unwanted situations where `MenuBar` sets nav focus
Ultimately the menu code still feels fragile (menus rely on the root `MenuBar` to open/close sub-menus and set navigation focus on mouse motion) but this fixes obvious issues.

More event-handling fixes

---

CHANGELOG.md
Cargo.toml
crates/kas-core/Cargo.toml
crates/kas-core/src/layout/align.rs
crates/kas-macros/Cargo.toml
crates/kas-macros/src/args.rs
crates/kas-theme/Cargo.toml
crates/kas-theme/src/config.rs
crates/kas-wgpu/Cargo.toml
crates/kas-wgpu/src/lib.rs
crates/kas-widgets/Cargo.toml
crates/kas-widgets/src/button.rs
examples/calculator.rs
examples/hello.rs
examples/markdown.rs
src/macros.rs

Apparently the 0.10 release was too hasty, resulting in two issues:

0.10.1: Fix button alignment/stretch, fix examples

---

crates/kas-core/src/updatable/filter.rs
crates/kas-macros/src/args.rs
crates/kas-macros/src/lib.rs
crates/kas-widgets/src/dialog.rs
examples/calculator.rs
examples/counter.rs
examples/custom-theme.rs
examples/data-list-view.rs
examples/data-list.rs
examples/filter-list.rs
examples/gallery.rs
examples/mandlebrot/mandlebrot.rs
examples/markdown.rs
examples/splitter.rs
examples/stopwatch.rs
examples/sync-counter.rs
src/macros.rs

Most significantly, the `#[widget(handler = f)]` argument `handler` is replaced with `use_msg`, `map_msg` and `flatmap_msg` arguments. This allows message handlers to return `()` or the new message type `M` or `Response<M>` respectively.
Also included: several small code simplifications/improvements.

Cleaner code; use_msg/map_msg/flatmap_msg

---

crates/kas-core/src/event/manager/mgr_pub.rs
crates/kas-core/src/toolkit.rs
crates/kas-core/src/updatable.rs
crates/kas-core/src/updatable/filter.rs
crates/kas-core/src/updatable/shared_rc.rs
crates/kas-macros/src/args.rs
crates/kas-macros/src/lib.rs
crates/kas-wgpu/src/shared.rs
crates/kas-wgpu/src/window.rs
crates/kas-widgets/src/view/driver.rs
crates/kas-widgets/src/view/filter_list.rs
crates/kas-widgets/src/view/list_view.rs
crates/kas-widgets/src/view/matrix_view.rs
crates/kas-widgets/src/view/mod.rs
crates/kas-widgets/src/view/single_view.rs
examples/data-list-view.rs
examples/filter-list.rs
src/macros.rs

- Replace `FilteredList` "data-view" with `FilterListView` widget
- Make filters simpler to use by making a shared data object
- Remove complex recursive-data-update machinery that was required by `FilteredList`
- Restore `Driver::get` data-model-update mechanism (thus making a simple interactive widget over shared data update that data by default)
- Add `#[widget(discard_msg)]` and `#[widget(update = f)]`

FilterListView; discard_msg and update; data/driver improvements

---

crates/kas-core/src/core/widget.rs
crates/kas-core/src/event/handler.rs
crates/kas-core/src/event/manager.rs
crates/kas-core/src/event/manager/mgr_shell.rs
crates/kas-core/src/event/mod.rs
crates/kas-core/src/layout/grid_solver.rs
crates/kas-core/src/layout/mod.rs
crates/kas-macros/src/layout.rs
crates/kas-macros/src/lib.rs
crates/kas-widgets/src/combobox.rs
crates/kas-widgets/src/grid.rs
crates/kas-widgets/src/lib.rs
crates/kas-widgets/src/list.rs
crates/kas-widgets/src/macros.rs
crates/kas-widgets/src/menu/menubar.rs
crates/kas-widgets/src/menu/submenu.rs
examples/counter.rs
examples/cursors.rs
examples/data-list.rs
examples/gallery.rs
examples/splitter.rs
examples/sync-counter.rs

Various smaller changes aimed at improving app code.
The `Grid` widget is not used and possibly not useful in practice: although it can do the layout of `layout(grid)`, it cannot easily handle multiple widget types (this requires boxing and explicit mapping of messages), it cannot currently do custom alignment (could be fixed easily), it cannot have message handlers (any attempt to fix this would have significant limitations compared to custom widgets, e.g. no (named) field access), and cannot enable alt-bypass (used in the calculator).

List vs IndexedList, row & column macros, doc fixes, misc

---

crates/kas-core/src/core/data.rs
crates/kas-core/src/data/shared_data.rs
crates/kas-core/src/dir.rs
crates/kas-core/src/event/events.rs
crates/kas-core/src/event/manager.rs
crates/kas-core/src/event/manager/mgr_pub.rs
crates/kas-core/src/event/manager/mgr_shell.rs
crates/kas-core/src/text/selection.rs
crates/kas-core/src/toolkit.rs
crates/kas-widgets/src/combobox.rs
crates/kas-widgets/src/editbox.rs
crates/kas-widgets/src/menu.rs
crates/kas-widgets/src/menu/menu_entry.rs
crates/kas-widgets/src/menu/menubar.rs
crates/kas-widgets/src/menu/submenu.rs

Fixes #253, and in general menu behaviour:
- close open menu when clicking menubar and when window loses focus
- tighter event handling: `TkAction::CLOSE` is no longer an acceptable way of closing a popup (was unused); remove `Event::NewPopup`; close all descendants of a popup before the popup itself
- restrict setting navigation focus on popup open/close to (mostly) keyboard input since with the mouse this is redundant or wrong
- clear character-input focus when clearing navigation focus
- rewrite handling of arrow-key input

Fix menu behaviour (#253)

---

.github/workflows/test.yml
Cargo.toml
README.md
crates/kas-core/Cargo.toml
crates/kas-core/src/draw/color.rs
crates/kas-core/src/event/manager.rs
crates/kas-core/src/event/manager/mgr_pub.rs
crates/kas-core/src/event/manager/mgr_shell.rs
crates/kas-dylib/Cargo.toml
crates/kas-dylib/src/lib.rs
crates/kas-macros/Cargo.toml
crates/kas-macros/src/lib.rs
crates/kas-resvg/Cargo.toml
crates/kas-resvg/src/svg.rs
crates/kas-theme/Cargo.toml
crates/kas-wgpu/Cargo.toml
crates/kas-wgpu/src/shared.rs
crates/kas-wgpu/src/window.rs
crates/kas-widgets/Cargo.toml
crates/kas-widgets/src/grid.rs
crates/kas-widgets/src/list.rs
crates/kas-widgets/src/view/filter_list.rs
examples/custom-theme.rs
examples/mandlebrot/Cargo.toml
examples/mandlebrot/mandlebrot.rs

- Bumps edition to 2021
- Bumps MSRV to 1.56 (required for edition)
- README: adds a section on data- vs widget-first design
- Fix: custom input bindings are prioritised over tab navigation
- Fix: `#[widget(update = f)]` now only calls `f` on `Response::Update` (this is unused, and may be removed later anyway)
- Apply or hide all Clippy suggestions
- Require Clippy pass in CI

Edition 2021, Clippy, README, fixes

---

crates/kas-wgpu/Cargo.toml

kas-wgpu depends on winit 0.26 which exposes raw-window-handle 0.4 types in its public API. As a result, wgpu (which exposes raw-window-handle 0.3 types in its public API) must be forced to use raw-window-handle 0.3.4, which is compatible with 0.4.x. Otherwise in projects with a stale Cargo.lock containing raw-window-handle <= 0.3.3 but latest kas-wgpu, you'll get a trait mismatch build error.
See https://github.com/kas-gui/kas/discussions/261.

Force wgpu to use raw-window-handle 0.3.4 for winit compatibility

---

crates/kas-macros/src/args.rs
crates/kas-macros/src/autoimpl.rs
crates/kas-macros/src/lib.rs
crates/kas-macros/src/make_layout.rs
crates/kas-macros/src/make_widget.rs
crates/kas-resvg/src/svg.rs
crates/kas-widgets/src/adapter/label.rs
crates/kas-widgets/src/adapter/map.rs
crates/kas-widgets/src/adapter/reserve.rs
crates/kas-widgets/src/button.rs
crates/kas-widgets/src/checkbox.rs
crates/kas-widgets/src/combobox.rs
crates/kas-widgets/src/edit_field.rs
crates/kas-widgets/src/frame.rs
crates/kas-widgets/src/menu/menu_entry.rs
crates/kas-widgets/src/nav_frame.rs
crates/kas-widgets/src/radiobox.rs
crates/kas-widgets/src/scroll.rs
crates/kas-widgets/src/scrollbar.rs
crates/kas-widgets/src/view/single_view.rs
crates/kas-widgets/src/window.rs
src/macros.rs

- `autoimpl` macro has slightly different syntax: `on self.field` or `skip self.field`
- `make_widget` macro now directly generates input struct for `widget` macro instead of generating code to be parsed again. This sped up `cargo check --examples` by about 2%.

macros: require 'self.' in autoimpl; better make_widget code

---

crates/kas-core/Cargo.toml
crates/kas-core/src/draw/draw_shared.rs
crates/kas-core/src/event/components.rs
crates/kas-core/src/event/events.rs
crates/kas-core/src/event/manager/mgr_pub.rs
crates/kas-core/src/event/manager/mgr_shell.rs
crates/kas-core/src/geom.rs
crates/kas-core/src/geom/vector.rs
crates/kas-core/src/layout/size_types.rs
crates/kas-core/src/layout/sizer.rs
crates/kas-core/src/layout/visitor.rs
crates/kas-core/src/prelude.rs
crates/kas-core/src/text.rs
crates/kas-resvg/src/canvas.rs
crates/kas-resvg/src/svg.rs
crates/kas-theme/src/dim.rs
crates/kas-theme/src/flat_theme.rs
crates/kas-theme/src/shaded_theme.rs
crates/kas-wgpu/src/draw/atlases.rs
crates/kas-wgpu/src/draw/draw_pipe.rs
crates/kas-wgpu/src/window.rs
crates/kas-widgets/src/drag.rs
crates/kas-widgets/src/edit_field.rs
crates/kas-widgets/src/label.rs
crates/kas-widgets/src/scroll_label.rs
crates/kas-widgets/src/view/filter_list.rs
examples/async-event.rs
examples/clock.rs
examples/mandlebrot/mandlebrot.rs

Uses easy-cast version from master for now

Use easy-cast traits for geometry types

---

.github/workflows/test.yml
README.md
crates/kas-core/src/core/impls.rs
crates/kas-core/src/core/widget.rs
crates/kas-core/src/event/manager.rs
crates/kas-core/src/geom.rs
crates/kas-core/src/layout/row_solver.rs
crates/kas-core/src/layout/sizer.rs
crates/kas-macros/src/lib.rs
crates/kas-macros/src/widget.rs
crates/kas-theme/src/anim.rs
crates/kas-widgets/src/adapter/adapt_widget.rs
crates/kas-widgets/src/adapter/mod.rs
crates/kas-widgets/src/menu.rs
examples/stopwatch.rs
src/lib.rs
src/prelude.rs

Widget methods which are not intended to support custom implementations were moved to `WidgetExt`, preventing custom implementation and reducing the size of a boxed widget's vtable.
Since `kas_widgets::adapter` *also* had a `WidgetExt` trait, the latter was renamed to `AdaptWidget`.
Edit: removed shared-data updates from this commit
<details>
Shared-data updates now rely on data versioning. Data version-numbers were already added in 89639f729e9edaeaea2b35c1d880df996310033d but not previously used. Now (possible since `fn draw` takes `&mut self`, due to the addition of `Layout::layout`) data versions are checked on draw and updated if necessary.
Advantages:
- (Minor) No need for data to have an `UpdateHandle`
- (Trivial) No need for view widgets to subscribe to updates
- (Major) Recursive …

WidgetExt; shared-data versioning model

---

crates/kas-core/src/core/widget.rs
crates/kas-core/src/updatable.rs
crates/kas-core/src/updatable/data_impls.rs
crates/kas-core/src/updatable/data_traits.rs
crates/kas-core/src/updatable/filter.rs
crates/kas-core/src/updatable/shared_rc.rs
crates/kas-core/src/util.rs
crates/kas-widgets/src/radiobox.rs
crates/kas-widgets/src/view/filter_list.rs
crates/kas-widgets/src/view/list_view.rs
crates/kas-widgets/src/view/matrix_view.rs
crates/kas-widgets/src/view/mod.rs
crates/kas-widgets/src/view/single_view.rs
examples/data-list-view.rs
examples/filter-list.rs
examples/times-tables.rs

Alternative to #288: give shared data a version counter *and* `UpdateHandle`(s).
Compared to #288:
- each shared-data trait has an `fn update_handles(&self) -> Vec<UpdateHandle>` method (rarely called hence the heap allocation is unimportant)
- shared-data view widgets must register for and handle `UpdateHandle`s, but don't need to check data version on draw
- we don't need to redraw everything simply because shared data changes
- shared-data implementations are a little bit more complex due to having an `UpdateHandle` and a version counter
Overall this is only slightly more complex and avoids "redraw the world on any shared data change", so is preferable.
Another option is to tweak the code in this PR by replacing `fn version` with `fn refresh` and remove data version counters:
- drop …

Shared data: version counter and UpdateHandle

---

crates/kas-core/Cargo.toml
crates/kas-core/src/event/handler.rs
crates/kas-core/src/layout/sizer.rs
crates/kas-macros/Cargo.toml
crates/kas-macros/src/lib.rs
crates/kas-macros/src/widget.rs
crates/kas-macros/src/widget_index.rs
crates/kas-resvg/Cargo.toml
crates/kas-resvg/src/svg.rs
crates/kas-wgpu/Cargo.toml
crates/kas-wgpu/src/window.rs
crates/kas-widgets/src/scrollbar.rs
crates/kas-widgets/src/window.rs
examples/markdown.rs

- Update dependencies (minor changes)
- `examples/markdown.rs`: remove button and update on typing
- add `widget_index!` macro for use within `widget!` macro

update deps, add widget_index!, improve examples/markdown

---

crates/kas-core/src/theme/draw.rs
crates/kas-macros/src/autoimpl.rs
crates/kas-macros/src/lib.rs
crates/kas-macros/tests/autoimpl.rs

Fixes #293 (reminder to self: compile-only tests are not a substitute for running tests).
Support for an explicit definitive type is removed completely. *Potentially* it could be useful in some contexts, e.g.:
```rust
#[autoimpl(for<'a> &'a mut (), Box<()> using <() as Z>)]
trait Z {
// ...
}
impl Z for () {
// ...
}
```
... *however* (1) `<() as Z>` does not parse as a type (`::` expected) and (2) the reason we can't deduce the definitive type here is because the re-implementation is for a specific target type, which is less useful in general. Thus, I choose to remove `using PartialType` syntax instead of supporting this case.

Fix use of autoimpl for dyn Trait

---

crates/kas-core/src/theme/draw.rs
crates/kas-core/src/theme/style.rs
crates/kas-macros/src/widget.rs
crates/kas-theme/src/config.rs
crates/kas-theme/src/dim.rs
crates/kas-theme/src/flat_theme.rs
crates/kas-theme/src/shaded_theme.rs
crates/kas-widgets/src/adapter/label.rs
crates/kas-widgets/src/edit_field.rs
crates/kas-widgets/src/label.rs
crates/kas-widgets/src/menu/menu_entry.rs
crates/kas-widgets/src/menu/submenu.rs
crates/kas-widgets/src/scroll.rs

- Simplify the theme's API slightly
- Fix accelerator-key underlines always being visible in the calculator
- Allow disabling line-wrapping for labels
- Fix not showing accelerator underlines without `Alt` for `AccelLabel` on stable Rust

Revise TextClass; remove DrawHandle::text_accel

---

crates/kas-core/src/core/widget.rs
crates/kas-core/src/event/manager.rs
crates/kas-core/src/event/manager/mgr_pub.rs
crates/kas-core/src/event/manager/mgr_shell.rs
crates/kas-core/src/geom.rs
crates/kas-core/src/geom/vector.rs
crates/kas-core/src/layout/mod.rs
crates/kas-core/src/layout/visitor.rs
crates/kas-resvg/src/svg.rs
crates/kas-theme/src/dim.rs
crates/kas-theme/src/flat_theme.rs
crates/kas-theme/src/shaded_theme.rs
crates/kas-wgpu/src/shared.rs
crates/kas-wgpu/src/window.rs
crates/kas-widgets/src/checkbox.rs
crates/kas-widgets/src/edit_field.rs

Wayland windows now have size calculated using scale-factor 1, then rescaled if necessary (required since Wayland only accepts logical coordinates; i.e. client has no control over scaled size). X11 and other platforms continue to use the guessed scale factor (at least on X11 this is the best option).
Add some documentation regarding configuration and scale factor.
Visual improvements:
- Revise margins, especially vertical margin in menus
- Use a check mark in `FlatTheme`
- Fix `EditBox` focus indicator; new effect in `ShadedTheme`

Fix initial window size on Wayland; visual improvements

---

crates/kas-core/src/core/widget.rs
crates/kas-core/src/event/manager.rs
crates/kas-core/src/event/manager/mgr_shell.rs
crates/kas-core/src/layout/mod.rs
crates/kas-core/src/toolkit.rs
crates/kas-core/src/updatable/data_traits.rs
crates/kas-widgets/src/combobox.rs
crates/kas-widgets/src/grid.rs
crates/kas-widgets/src/list.rs
crates/kas-widgets/src/menu/submenu.rs
crates/kas-widgets/src/splitter.rs
crates/kas-widgets/src/stack.rs
crates/kas-widgets/src/view/driver.rs
crates/kas-widgets/src/view/list_view.rs
crates/kas-widgets/src/view/matrix_view.rs
crates/kas-widgets/src/view/single_view.rs
examples/data-list.rs
examples/gallery.rs
examples/splitter.rs

`List`, `Stack`, `ComboBox` and `Splitter` widgets now locally reconfigure new children without changing the `WidgetId` of other children (they use a `HashMap` for `WidgetId` → `child_index` lookup).
The result (using `example/data-list.rs` and a hand-controlled stopwatch):
| | before | after |
|- | -| -|
| from 0 to 100,000 | 17.6s | 17.8s |
| from 100,000 to 100,001 | 13.8s | 0.6s |
Full-window resize is still required after adjusting the number of widgets, but apparently this is clearly much faster than configuring widgets (a little surprising since configuring is mostly just assigning a `WidgetId`).
TODO: `ComboBox` doesn't need to resize the window if the menu is closed, and only needs to resize the menu if open, but it inherits the full-window resize from `List`. (Low impact …

Restore configure_recurse; use local reconfigure for dynamic parents

---

crates/kas-core/src/core/widget.rs
crates/kas-core/src/event/manager/mgr_shell.rs
crates/kas-core/src/geom.rs
crates/kas-core/src/geom/vector.rs
crates/kas-core/src/layout/mod.rs
crates/kas-core/src/layout/row_solver.rs
crates/kas-macros/src/args.rs
crates/kas-macros/src/lib.rs
crates/kas-macros/src/widget.rs
crates/kas-theme/src/flat_theme.rs
crates/kas-theme/src/shaded_theme.rs
crates/kas-widgets/src/adapter/label.rs
crates/kas-widgets/src/checkbox.rs
crates/kas-widgets/src/combobox.rs
crates/kas-widgets/src/list.rs
crates/kas-widgets/src/menu.rs
crates/kas-widgets/src/menu/menu_entry.rs
crates/kas-widgets/src/menu/menubar.rs
crates/kas-widgets/src/menu/submenu.rs
crates/kas-widgets/src/radiobox.rs
crates/kas-widgets/src/splitter.rs
crates/kas-widgets/src/stack.rs
crates/kas-widgets/src/view/list_view.rs
crates/kas-widgets/src/view/matrix_view.rs
examples/stopwatch.rs

Replace `Widget::configure_recurse` with `make_child_id`, `pre_configure`. More user-friendly: it's not required to replace `configure_recurse` impl when changing only one part of its behaviour.
Remove `WidgetCore::core_data` and `core_data_mut` methods: widgets still have a `core` field, but its type is no longer fixed. An unorthodox tactic was used to achieve this: the "default implementations" of `pre_configure` and `set_rect` are now generated by the `#[widget]` macro. This should "just work", but one issue was discovered: (unstable) specialization allows multiple implementations of traits (such as `Widget`), only the most general of which is required to be complete. We use the simplest "fix" possible: only write default implementations into the *first* implementation of the `Widget` …

Trait revision, part 2: remove configure_recurse, core_data[_mut]

---

crates/kas-macros/README.md
crates/kas-macros/src/args.rs
crates/kas-macros/src/impl_singleton.rs
crates/kas-macros/src/lib.rs
crates/kas-macros/src/make_layout.rs
crates/kas-macros/src/make_widget.rs
crates/kas-macros/src/widget.rs
examples/calculator.rs
examples/counter.rs
examples/custom-theme.rs
examples/data-list-view.rs
examples/data-list.rs
examples/filter-list.rs
examples/gallery.rs
examples/layout.rs
examples/markdown.rs
examples/splitter.rs
examples/stopwatch.rs
examples/sync-counter.rs
examples/times-tables.rs

What was `make_widget` is made more generic, no longer being special to widgets (aside from a rule for `#[widget]` fields which adds the `Widget` trait bound):
- do not add `widget_core!()` field or derive `Debug` automatically
- construct values using `Default::default()` if omitted
- make locally-declared type parameter names unique
- rename to `impl_singleton`
- support unit and tuple structs

make_widget → impl_singleton

---

crates/kas-core/Cargo.toml
crates/kas-core/src/core/widget.rs
crates/kas-core/src/draw/draw.rs
crates/kas-core/src/event/manager/config_mgr.rs
crates/kas-core/src/text.rs
crates/kas-core/src/text/string.rs
crates/kas-core/src/theme/draw.rs
crates/kas-core/src/theme/size.rs
crates/kas-macros/src/make_layout.rs
crates/kas-theme/src/dim.rs
crates/kas-theme/src/lib.rs
crates/kas-theme/src/simple_theme.rs
crates/kas-theme/src/theme_dst.rs
crates/kas-wgpu/Cargo.toml
crates/kas-wgpu/src/draw/text_pipe.rs
crates/kas-widgets/src/check_box.rs
crates/kas-widgets/src/edit_field.rs
crates/kas-widgets/src/label.rs
crates/kas-widgets/src/radio_box.rs
crates/kas-widgets/src/scroll_bar.rs
crates/kas-widgets/src/scroll_label.rs
examples/async-event.rs
examples/clock.rs
examples/gallery.rs
examples/layout.rs
examples/times-tables.rs

Adds the `SimpleTheme`. Ugly, but potentially useful as a base for developing other themes. Currently this uses the same dimensions as `FlatTheme`.
- Fix for scroll bars drawn over other content
- KAS-text: various API tweaks: https://github.com/kas-gui/kas-text/pull/68
- Text: combine `dpp` and `pt_size` parameters
- Check/radio buttons: layout direction inferred from text label (i.e. reversed for RTL texts)

SimpleTheme, KAS-text updates

---

Cargo.toml
crates/kas-core/Cargo.toml
crates/kas-core/src/draw/draw.rs
crates/kas-core/src/draw/draw_shared.rs
crates/kas-core/src/geom/vector.rs
crates/kas-core/src/theme/draw.rs
crates/kas-theme/Cargo.toml
crates/kas-theme/src/colors.rs
crates/kas-theme/src/flat_theme.rs
crates/kas-theme/src/shaded_theme.rs
crates/kas-theme/src/simple_theme.rs
crates/kas-wgpu/Cargo.toml
crates/kas-wgpu/src/draw/draw_pipe.rs
crates/kas-wgpu/src/draw/text_pipe.rs
crates/kas-widgets/src/edit.rs
crates/kas-widgets/src/scroll_label.rs
examples/clock.rs

Fixes text clamping for scrolled text (`ScrollLabel`, `EditField`) broken in #336.
Add [dark-light](https://crates.io/crates/dark-light) as an optional dependency to automatically use dark mode.

Auto-detect dark theme; fix text clamping

---

README.md
crates/kas-core/src/model/data_traits.rs
crates/kas-view/src/driver.rs
crates/kas-view/src/lib.rs
crates/kas-view/src/list_view.rs
crates/kas-view/src/matrix_view.rs
crates/kas-view/src/single_view.rs

Also: fully reset view widgets when changing data binding. This fixes weird issues with text cursor/selection carrying over to new entries when scrolling `examples/data-list-view` at the cost of also clearing this state for the original entry when scrolling back (an argument for moving this state up to the event viewer, though that approach could only work for "blessed" types of widget interaction state).

README, model/view docs

---

.github/workflows/test.yml
CHANGELOG.md
Cargo.toml
crates/kas-core/Cargo.toml
crates/kas-core/src/event/manager/mgr_pub.rs
crates/kas-core/src/root.rs
crates/kas-core/src/text/string.rs
crates/kas-view/src/list_view.rs
crates/kas-view/src/matrix_view.rs
crates/kas-wgpu/Cargo.toml
crates/kas-wgpu/src/window.rs
crates/kas-widgets/Cargo.toml
crates/kas-widgets/src/edit.rs
crates/kas-widgets/src/scroll_bar.rs
crates/kas-widgets/src/spinner.rs
examples/gallery.rs

Use [`PresentMode::Fifo`](https://docs.rs/wgpu/latest/wgpu/struct.SurfaceConfiguration.html#structfield.present_mode). This is documented as the only supported mode. Fixes #367 and #368. Unfortunately this presents another issue: hang on exit on X11 in some circumstances (related to usage of multiple windows). I believe this is a WGPU issue: https://github.com/gfx-rs/wgpu/issues/1446
Also fix a couple of issues reported [on reddit](https://www.reddit.com/r/rust/comments/zl69lo/kas_rust_state_of_gui/j0nauao/):
- Mouse focus/highlighting for Spinner widget
- Show mnemonic labels when an edit box has input focus
- Update docs to use "mnemonics"
Note: other fixes would be breaking changes and/or significant work and are post-poned.

Small fixes

---

crates/kas-core/Cargo.toml
crates/kas-core/src/shell/common.rs
crates/kas-core/src/shell/shell.rs
crates/kas-core/src/shell/window.rs
crates/kas-core/src/theme/colors.rs
crates/kas-macros/Cargo.toml
crates/kas-resvg/Cargo.toml
crates/kas-resvg/src/svg.rs
crates/kas-wgpu/Cargo.toml
crates/kas-wgpu/src/draw/atlases.rs
crates/kas-wgpu/src/draw/draw_pipe.rs
crates/kas-wgpu/src/surface.rs

Update to use the pending winit release, wgpu 0.15 and dark-light 1.0.
Uses https://github.com/hecrj/window_clipboard/pull/20.

Update winit, wgpu, dark-light, window_clipboard

---

CHANGELOG.md
Cargo.toml
crates/kas-core/Cargo.toml
crates/kas-core/src/theme/style.rs
crates/kas-dylib/Cargo.toml
crates/kas-macros/Cargo.toml
crates/kas-resvg/Cargo.toml
crates/kas-view/Cargo.toml
crates/kas-wgpu/Cargo.toml
crates/kas-widgets/Cargo.toml
examples/mandlebrot/Cargo.toml

-   Add `EventMgr::push_async`, `push_spawn` (#376)
-   Support transparent windows (#380)
-   Support borderless windows and basic toolkit-drawn titlebar (#380)
-   Move theme traits, `SimpleTheme` and `FlatTheme` to kas-core (#374)
-   Move `ShadedTheme` to kas-wgpu (#374)
-   Move `Shell` to kas-core. Add `WindowSurface`, `GraphicalShell`,  `ShellAssoc` traits for better abstraction of shell implementation. Add `kas::shell::DefaultShell`. (#375)
-   Rename `ToolkitProxy` → `Proxy`, `TkAction` → `Action` (#375)
-   `Widget::handle_message` is now called on the widget submitting a message (#376)
-   `Canvas` uses async rendering (#376)
-   `Svg` uses async rendering (#378)
-   Update to Winit 0.28, Wgpu 0.15, dark-light 1.0 (#379)
-   Improved momentum scrolling (#381)

Prepare 0.13.0

---

CHANGELOG.md
crates/kas-core/Cargo.toml
crates/kas-core/build.rs
crates/kas-core/src/event/components.rs
crates/kas-core/src/event/events.rs
crates/kas-core/src/event/manager.rs
crates/kas-core/src/event/manager/mgr_pub.rs
crates/kas-core/src/event/manager/mgr_shell.rs
crates/kas-core/src/event/manager/press.rs
crates/kas-core/src/event/mod.rs
crates/kas-core/src/shell/common.rs
crates/kas-core/src/shell/shared.rs
crates/kas-core/src/shell/window.rs
crates/kas-view/src/list_view.rs
crates/kas-view/src/matrix_view.rs
crates/kas-widgets/src/combobox.rs
crates/kas-widgets/src/edit.rs
crates/kas-widgets/src/grip.rs
crates/kas-widgets/src/menu/menubar.rs
crates/kas-widgets/src/scroll_bar.rs
crates/kas-widgets/src/scroll_label.rs
crates/kas-widgets/src/slider.rs
examples/mandlebrot/mandlebrot.rs

#382 was not released due to the window_clipboard dependency. This PR replaces that with arboard + smithay-clipboard, and:
- supports the primary buffer on Linux
- adds `Press::grab` builder pattern

Replace clipboard, primary buffer, Press::grab, new 0.13.0 release

---

.github/workflows/test.yml
Cargo.toml
crates/kas-core/Cargo.toml
crates/kas-core/src/draw/draw_shared.rs
crates/kas-core/src/shell/common.rs
crates/kas-core/src/shell/mod.rs
crates/kas-core/src/shell/shell.rs
crates/kas-core/src/shell/window.rs
crates/kas-dylib/Cargo.toml
crates/kas-resvg/Cargo.toml
crates/kas-wgpu/Cargo.toml
crates/kas-wgpu/README.md
crates/kas-wgpu/src/draw/draw_pipe.rs
crates/kas-wgpu/src/draw/text_pipe.rs
crates/kas-wgpu/src/lib.rs
examples/mandlebrot/mandlebrot.rs
src/lib.rs

Some of the crates released at 0.13.0 don't compile with default features; test those and fix.
Add "stable" feature for kas, kas-core and use in tests and docs.rs.

Revise crate features; improve CI tests

---

.github/workflows/test.yml
crates/kas-core/src/core/impls.rs
crates/kas-core/src/core/layout.rs
crates/kas-core/src/core/node.rs
crates/kas-core/src/core/widget.rs
crates/kas-core/src/event/config/shortcuts.rs
crates/kas-core/src/event/cx/cx_pub.rs
crates/kas-core/src/event/cx/cx_shell.rs
crates/kas-core/src/event/cx/mod.rs
crates/kas-core/src/event/events.rs
crates/kas-core/src/event/mod.rs
crates/kas-core/src/root.rs
crates/kas-core/src/theme/colors.rs
crates/kas-view/src/list_view.rs
crates/kas-view/src/matrix_view.rs
crates/kas-widgets/src/combobox.rs
crates/kas-widgets/src/dialog.rs
crates/kas-widgets/src/edit.rs
crates/kas-widgets/src/menu/menubar.rs
crates/kas-widgets/src/menu/submenu.rs
crates/kas-widgets/src/slider.rs
crates/kas-widgets/src/spinner.rs

This lets widgets get direct access to Winit's new key events and fixes issues conflating text entry with shortcuts or control characters.
See also https://github.com/rust-windowing/winit/issues/3038. This impl directly modifies `event.text` but we should probably align with Winit.
Edit to clarify: this code sets `KeyEvent::Text` to `None` where the text would be non-printable (control codes) or should only be matched as a shortcut (due to usage of Ctrl/Super/Alt keys). This approach may need to be changed.

Replace Event::Text with Event::Key

---

Cargo.toml
crates/kas-core/src/action.rs
crates/kas-core/src/core/widget.rs
crates/kas-core/src/draw/draw_shared.rs
crates/kas-core/src/event/cx/config.rs
crates/kas-core/src/event/cx/cx_pub.rs
crates/kas-core/src/event/cx/cx_shell.rs
crates/kas-core/src/event/cx/mod.rs
crates/kas-core/src/event/cx/press.rs
crates/kas-core/src/root.rs
crates/kas-core/src/shell/common.rs
crates/kas-core/src/shell/event_loop.rs
crates/kas-core/src/shell/mod.rs
crates/kas-core/src/shell/shared.rs
crates/kas-core/src/shell/shell.rs
crates/kas-core/src/shell/window.rs
crates/kas-core/src/theme/draw.rs
crates/kas-macros/src/lib.rs
crates/kas-macros/src/widget.rs
crates/kas-resvg/src/canvas.rs
crates/kas-resvg/src/svg.rs
crates/kas-view/src/filter/filter_list.rs
crates/kas-view/src/list_view.rs
crates/kas-view/src/matrix_view.rs
crates/kas-widgets/src/spinner.rs
crates/kas-widgets/src/splitter.rs
crates/kas-widgets/src/tab_stack.rs

This updates to Winit master which fixes a touch-move bug (on Wayland).
Also fixes a bug with drag-opening a `ComboBox` menu. This was caused by re-ordering of pending actions resulting in an attempt to navigate to the first child of the menu before configuration. Originally the intention here was to use only a single pending list to avoid all re-ordering, but this PR takes a more limited solution:
`PressMove` events are sent immediately, instead of attempting to batch them (actual batching was already disabled). This may result in performance issues when rapidly scrolling a `ListView` which will require a more specific solution.
Behaviour change for attempting to grab mouse / touch input twice in a row to better handle the the odd place this does happen.

Cleaner handling of pendling events; update Winit

---

.github/workflows/test.yml
crates/kas-core/Cargo.toml
crates/kas-core/src/draw/draw_shared.rs
crates/kas-core/src/shell/common.rs
crates/kas-core/src/shell/mod.rs
crates/kas-core/src/shell/shared.rs
crates/kas-core/src/shell/shell.rs
crates/kas-core/src/shell/window.rs
crates/kas-resvg/src/svg.rs
crates/kas-wgpu/Cargo.toml
crates/kas-wgpu/src/draw/draw_pipe.rs
crates/kas-wgpu/src/surface.rs

Fixes #415 
Unfortunately we cannot use WGPU 0.18 due to https://github.com/gfx-rs/wgpu/issues/4569.

WGPU update, improved window creation

---

crates/kas-core/src/shell/mod.rs
crates/kas-core/src/theme/config.rs
crates/kas-core/src/theme/dimensions.rs
crates/kas-macros/src/widget.rs
crates/kas-widgets/src/adapt/adapt_events.rs
crates/kas-widgets/src/adapt/adapt_widget.rs
crates/kas-widgets/src/lib.rs
crates/kas-widgets/src/scroll_text.rs
examples/gallery.rs

Most notable is probably the `ScrollText` widget, requested in #415 (CC @m-hugo). Not currently used.
Font sizes probably shouldn't use old imperial units intended for publishing on paper (even if Windows and many Linux DEs still do).

ScrollText widget, font sizes in pixels, AdaptWidget::on_messages, misc fixes

---

crates/kas-core/Cargo.toml
crates/kas-core/src/shell/common.rs
crates/kas-core/src/shell/mod.rs
crates/kas-core/src/shell/window.rs
crates/kas-resvg/Cargo.toml
crates/kas-wgpu/Cargo.toml
crates/kas-wgpu/src/surface.rs

This rolls back raw-window-handle to 0.5.0 since this is the version supported by the last WGPU release.
This PR should enable a KAS release (after updating the CHANGELOG), though I may make a few other changes first.

Use WGPU 0.18.1; updates

---

crates/kas-wgpu/Cargo.toml
crates/kas-wgpu/src/draw/shaded_square.rs
crates/kas-wgpu/src/draw/shaders.rs

This results in approximately 3% decrease in binary size. Testing the `gallery` example:
Old sizes
Debug build: 321M (37M=38182856 stripped)
Release build: 24412192 (14517808 stripped)
GSL only
Debug build: 336350520 (38185560 stripped)
Release build: 24414888 (14520544 stripped)
Without WGSL
Debug build: 331809320 (37205936 stripped)
Release build: 23913536 (14090504 stripped)

Remove WGSL feature

---

crates/kas-core/src/core/impls.rs
crates/kas-core/src/core/node.rs
crates/kas-core/src/core/widget.rs
crates/kas-core/src/event/cx/config.rs
crates/kas-core/src/event/cx/cx_pub.rs
crates/kas-core/src/event/cx/mod.rs
crates/kas-core/src/event/cx/platform.rs
crates/kas-core/src/event/events.rs
crates/kas-core/src/hidden.rs
crates/kas-macros/src/widget.rs
crates/kas-view/src/list_view.rs
crates/kas-view/src/matrix_view.rs
crates/kas-widgets/src/button.rs
crates/kas-widgets/src/check_box.rs
crates/kas-widgets/src/combobox.rs
crates/kas-widgets/src/edit.rs
crates/kas-widgets/src/grid.rs
crates/kas-widgets/src/list.rs
crates/kas-widgets/src/menu/menu_entry.rs
crates/kas-widgets/src/menu/submenu.rs
crates/kas-widgets/src/nav_frame.rs
crates/kas-widgets/src/radio_box.rs
crates/kas-widgets/src/scroll_bar.rs
crates/kas-widgets/src/slider.rs
crates/kas-widgets/src/spinner.rs
crates/kas-widgets/src/splitter.rs
crates/kas-widgets/src/tab_stack.rs
examples/gallery.rs

- Add `fn EventState::send<M: Debug + 'static>(&mut self, id: Id, msg: M)` to send a type-erased message to a designated target
- Add `fn ConfigCx::push<M: Debug + 'static>(&mut self, id: Id, msg: M)` to emit a type-erased message from configure/update
Currently the second method is just a wrapper around the first, but (a) there might be a distinction between "push/emit a reusable message" and "send a non-reusable message" in the future and (b) `ConfigCx` *might* gain an embedded `Id` for the current widget, in which case `push` would lose the `id` parameter (but `send` would not).
> [handle_messages impls: do not expect cx.last_child().is_some()](https://github.com/kas-gui/kas/commit/6791f6e9592fe63fa97ab9af633cbfc13a51ca29)
Since it's now possible to *send* a message, `handle_messages` …

Support message sending

---

crates/kas-core/src/event/cx/config.rs
crates/kas-core/src/event/cx/cx_pub.rs
crates/kas-core/src/messages.rs
crates/kas-macros/src/make_layout.rs
crates/kas-macros/src/widget.rs
crates/kas-view/src/driver.rs
crates/kas-view/src/list_view.rs
crates/kas-view/src/matrix_view.rs
crates/kas-widgets/src/adapt/adapt_events.rs
crates/kas-widgets/src/adapt/adapt_widget.rs
crates/kas-widgets/src/combobox.rs
crates/kas-widgets/src/grid.rs
crates/kas-widgets/src/list.rs
crates/kas-widgets/src/tab_stack.rs
crates/kas-widgets/src/text.rs

`AdaptEvents` is now a special thin wrapper over the inner widget. Implications:
- It does not have its own `Id`
- Introspection over a tree with an `AdaptEvents`-wrapped widget would see a different `widget_name` (affecting debug output) but otherwise identical tree, assuming the wrapper did not use any message handlers
- Usage of `EventCx::last_child` from `AdaptEvents` now works as expected (instead of just returning the index of the wrapped child, 0)
The latter is the main motivation, and makes it unnecessary to have message handler support in `Grid` and `List` (which could be confusing in practice without also supporting `.on_configure` and `.on_update` on those types).
This exposed a couple of potential issues in `ComboBox` which were fixed.
Also: add `fn EventCx::try_debug` to …

Make AdaptEvents a thin wrapper over an inner widget

---

crates/kas-core/src/core/collection.rs
crates/kas-core/src/core/mod.rs
crates/kas-core/src/layout/row_solver.rs
crates/kas-core/src/layout/visitor.rs
crates/kas-macros/src/collection.rs
crates/kas-macros/src/lib.rs
crates/kas-macros/src/make_layout.rs
crates/kas-widgets/src/combobox.rs
crates/kas-widgets/src/label.rs
crates/kas-widgets/src/lib.rs
crates/kas-widgets/src/list.rs
crates/kas-widgets/src/menu/menubar.rs
crates/kas-widgets/src/splitter.rs
crates/kas-widgets/src/tab_stack.rs
examples/data-list.rs
examples/gallery.rs
examples/splitter.rs

Adds a trait representing a "list of widgets", e.g. `Vec<W>` or a struct where each field is a widget.
Adds `kas::collection!` to generate an anonymous implementation and instance of a `Collection`.
Adjusts `List` and `Splitter` widgets to use `Collection`; as such they no longer have the restriction that each child must have the same type.
Uses this to rewrite the Gallery's editor to use a `Splitter` and not use a custom widget.

Add Collection trait

---

crates/kas-core/src/app/mod.rs
crates/kas-core/src/app/shared.rs
crates/kas-core/src/event/cx/cx_pub.rs
crates/kas-core/src/messages.rs
crates/kas-core/src/theme/config.rs
crates/kas-widgets/src/adapt/adapt.rs
examples/gallery.rs
examples/proxy.rs
examples/stopwatch.rs
examples/sync-counter.rs

`fn AppData::handle_messages` previously returned `Action`, however:
- The only sensible return values are `Action::empty()` and `Action::UPDATE`, hence we could replace with `bool`
- Assuming `UPDATE` when any message was removed from the stack is a good enough approximation, hence we don't need a return value at all
Similarly, `Adapt`'s message and timer handlers can also get away without using any return values (on the assumption that a timer is only requested when it is likely that something will happen, and that `Adapt` only makes things happen by adjusting its state; these appear reasonable assumptions given the intended usages).
Also, replace a couple more instances of custom widgets in examples.
Also increase the default font size to 16px (12pt).

Remove return values on some closures; replace some custom widgets

---

.github/workflows/test.yml
Cargo.toml
README.md
crates/kas-view/src/data_impls.rs
crates/kas-view/src/data_traits.rs
crates/kas-view/src/filter/filter_list.rs
crates/kas-view/src/list_view.rs
crates/kas-widgets/src/edit.rs
crates/kas-widgets/src/tab_stack.rs
examples/data-list-view.rs
examples/times-tables.rs

Some fixes to reduce resize/set_size in `examples/data-list-view.rs`.
Bump MSRV to 1.75 and make use of RPITIT.
Note: it is possible to also use RPITIT for `SharedData::borrow`, *but* since there is (currently) no mechanism to refer to the return type, it is impossible to specify (refine) that `UnsafeFilteredList::borrow` returns the same `ItemRef` type as the inner `SharedData`. This causes some minor issues due to the looser lifetime specification. Further, `SharedData::borrow` carries useful documentation. It also does not appear to simplify implementations much. It is therefore decided not to use RPITIT here.

MSRV=1.75: RPITIT; fixes

---

Cargo.toml
crates/kas-core/Cargo.toml
crates/kas-core/src/app/app.rs
crates/kas-core/src/app/common.rs
crates/kas-core/src/app/event_loop.rs
crates/kas-core/src/app/mod.rs
crates/kas-core/src/app/shared.rs
crates/kas-core/src/app/window.rs
crates/kas-resvg/Cargo.toml
crates/kas-resvg/src/svg.rs
crates/kas-wgpu/Cargo.toml
crates/kas-wgpu/src/draw/draw_pipe.rs
crates/kas-wgpu/src/lib.rs
crates/kas-wgpu/src/options.rs
crates/kas-wgpu/src/surface.rs
examples/mandlebrot/Cargo.toml
examples/mandlebrot/mandlebrot.rs

It turns out that examples were failing on X11 with a confusing message. https://github.com/rust-windowing/winit/pull/3414 fixes the message; this PR adds X11 to the default feature selection.
Update dependencies: `env_logger`, `cfg_aliases`, `resvg` and most significantly `wgpu`.
Safe handling of the window/surface lifetime. For now this uses `Arc<winit::window::Window>` to ensure the window outlives the surface. A true (efficient) solution would be closer to the self-referential struct problem (though without the aliasing and pinning sub-problems); essentially we could "just" cast the lifetime to `'static`, however there's no good way to do this without making `new_surface` unsafe or depend on WGPU (having `wgpu::SurfaceTarget` in `raw-window-handle` would help).

Update deps and enable winit/x11 by default

---

crates/kas-macros/src/make_layout.rs

#438 allowed layout macros to parse any method call on a layout object, translated verbatim to a method call on the generated `Visitor` object. This is potentially undesirable (already `.pack(hints)` is translated to `.pack(hints, storage)` for some generated `storage` object and `.map_all()` adjusts macro expansion instead of translating to a method call). This PR adds direct support for parsing `.align(hints)` and removes support for translating method calls verbatim.
Note: all these method calls *emulate* methods available on widget objects. `rust-analyzer` appears to link `.pack` and `.align` to the emulated method of `AdaptWidget` instead of the actually-used method on `Visitor` (possibly a bug, but it's acceptable here). The `.map_all()` method is not linked to anything (not …

Restrict possible method calls on layout objects

---

Cargo.toml
crates/kas-core/Cargo.toml
crates/kas-core/src/geom.rs
crates/kas-core/src/lib.rs
crates/kas-macros/Cargo.toml
crates/kas-macros/src/lib.rs
crates/kas-macros/src/make_layout.rs
crates/kas-widgets/src/lib.rs
crates/kas-widgets/src/list.rs
examples/calculator.rs
examples/counter.rs
examples/data-list-view.rs
examples/data-list.rs
examples/gallery.rs
examples/layout.rs
examples/splitter.rs
examples/stopwatch.rs
examples/sync-counter.rs
examples/times-tables.rs
tests/layout_macros.rs

Layout macros (`column!`, `grid!` etc.) are moved into the `kas::widgets` namespace.
These layout macros no longer recurse internally (except with feature `recursive-layout-widgets`). This is slightly less optimal but means that e.g. `column!["title", row!["a", "b"].map(|_| &())]` is now possible since the internal `row![..]` is a widget and thus supports all the usual methods. Caveat: this is incompatible with the `recursive-layout-widgets` feature, and thus we warn about it in all cases.
Note that recursive layout macros must remain a feature to support usage in custom widgets where inner layout components may refer to fields of the custom widget, so all we're really doing is turning off this feature in the common case to improve diagnostic output.
Since these macros now behave (mostly) …

Move layout macros to kas-widgets; do not recurse internally

---

crates/kas-core/src/core/collection.rs
crates/kas-core/src/core/mod.rs
crates/kas-core/src/decorations.rs
crates/kas-core/src/event/cx/cx_pub.rs
crates/kas-core/src/event/cx/mod.rs
crates/kas-core/src/event/cx/platform.rs
crates/kas-core/src/layout/grid_solver.rs
crates/kas-core/src/layout/mod.rs
crates/kas-core/src/layout/visitor.rs
crates/kas-core/src/lib.rs
crates/kas-core/src/theme/draw.rs
crates/kas-macros/src/collection.rs
crates/kas-macros/src/lib.rs
crates/kas-macros/src/make_layout.rs
crates/kas-macros/src/widget.rs
crates/kas-view/src/list_view.rs
crates/kas-view/src/matrix_view.rs
crates/kas-wgpu/src/draw/draw_pipe.rs
crates/kas-widgets/src/grid.rs
crates/kas-widgets/src/lib.rs
crates/kas-widgets/src/list.rs
crates/kas-widgets/src/menu/submenu.rs
crates/kas-widgets/src/spinner.rs
examples/clock.rs

- Rename `GridChildInfo` → `GridCellInfo`
- Add `trait CellCollection`, macro `cell_collection!`
- Some fixes

Add CellCollection for use by Grid

---

crates/kas-core/src/app/window.rs
crates/kas-macros/src/lib.rs

It turns out that the clock example wouldn't run at all on X11 due to a missing resize, so we should do that anyway (even though it may be redundant). If we had more platform-specific code here, we should be able to avoid this issue on Wayland at least. See github.com/rust-windowing/winit/issues/3192

Fix window sizing

---

Cargo.toml
crates/kas-core/src/decorations.rs
crates/kas-core/src/event/cx/config.rs
crates/kas-core/src/hidden.rs
crates/kas-core/src/layout/mod.rs
crates/kas-core/src/text/mod.rs
crates/kas-core/src/theme/config.rs
crates/kas-core/src/theme/dimensions.rs
crates/kas-core/src/theme/draw.rs
crates/kas-core/src/theme/flat_theme.rs
crates/kas-core/src/theme/simple_theme.rs
crates/kas-core/src/theme/size.rs
crates/kas-macros/src/extends.rs
crates/kas-resvg/src/svg.rs
crates/kas-wgpu/src/draw/text_pipe.rs
crates/kas-wgpu/src/shaded_theme.rs
crates/kas-widgets/src/check_box.rs
crates/kas-widgets/src/edit.rs
crates/kas-widgets/src/label.rs
crates/kas-widgets/src/radio_box.rs
crates/kas-widgets/src/scroll_label.rs
crates/kas-widgets/src/scroll_text.rs
crates/kas-widgets/src/text.rs
examples/clock.rs
examples/proxy.rs

Corresponding PRs:
- https://github.com/kas-gui/kas-text/pull/81
- https://github.com/kas-gui/kas-text/pull/82

kas-text revisions: text_is_rtl, configure, wrap_width, remove Environment, fonts::library

---

.github/workflows/test.yml
CHANGELOG.md
Cargo.toml
README.md
ROADMAP.md
crates/kas-core/Cargo.toml
crates/kas-core/src/config/font.rs
crates/kas-core/src/event/cx/config.rs
crates/kas-core/src/event/cx/cx_pub.rs
crates/kas-core/src/theme/simple_theme.rs
crates/kas-dylib/Cargo.toml
crates/kas-macros/Cargo.toml
crates/kas-resvg/Cargo.toml
crates/kas-resvg/src/svg.rs
crates/kas-view/Cargo.toml
crates/kas-wgpu/Cargo.toml
crates/kas-widgets/Cargo.toml
crates/kas-widgets/src/label.rs
crates/kas-widgets/src/lib.rs
crates/kas-widgets/src/list.rs
examples/gallery.rs
examples/mandlebrot/Cargo.toml
examples/sync-counter.rs

Also, remove:
- fns `label`, `label_any` (unnecessary wrappers over `Label` methods)
- `ConfigCx::push`, `push_erased` (redundant with `EventState::send{_erased}`)

Use kas-text 0.7.0; prepare 0.15.0

---

.github/workflows/test.yml
Cargo.toml
crates/kas-core/Cargo.toml
crates/kas-core/src/config/format.rs
crates/kas-macros/Cargo.toml
crates/kas-macros/src/widget_derive.rs
crates/kas-widgets/src/list.rs

This includes:
- a small fix to #460
- a `kas-macros/nightly` feature to enable reporting warnings (a workaround until https://github.com/GnomedDev/proc-macro-error-2/pull/5 lands)
- replaces the deprecated `serde_yaml` dependency
- a fix to the `List` widget

Fixes + serde_yaml2

---

.github/workflows/test.yml
Cargo.toml
crates/kas-core/Cargo.toml
crates/kas-core/src/core/layout.rs
crates/kas-core/src/hidden.rs
crates/kas-core/src/layout/mod.rs
crates/kas-core/src/layout/visitor.rs
crates/kas-macros/src/make_layout.rs
crates/kas-macros/src/widget_args.rs
crates/kas-macros/src/widget_derive.rs
crates/kas-widgets/src/adapt/adapt_events.rs

Also don't support `impl Widget` for `#[widget{ derive = ..; }]`.

Add feature nightly-diagnostics; improve macro error msgs

---

crates/kas-core/src/core/widget.rs
crates/kas-core/src/event/cx/config.rs
crates/kas-core/src/event/cx/cx_pub.rs
crates/kas-core/src/messages.rs
crates/kas-widgets/src/combobox.rs

Use common nomenclature.
Also remove a note about an intended TODO item: there is not good motivation to add `fn ConfigCx::push` as sugar for `cx.send(self.id(), msg)`.

Rename try_observe -> try_peek

---

.github/workflows/test.yml
Cargo.toml
README.md
crates/kas-core/src/action.rs
crates/kas-core/src/event/cx/cx_pub.rs
crates/kas-core/src/event/cx/mod.rs
crates/kas-core/src/event/cx/platform.rs
crates/kas-core/src/root.rs
crates/kas-core/src/runner/event_loop.rs
crates/kas-core/src/runner/mod.rs
crates/kas-core/src/runner/shared.rs
crates/kas-core/src/runner/window.rs
crates/kas-wgpu/Cargo.toml
crates/kas-wgpu/src/draw/draw_pipe.rs
crates/kas-wgpu/src/draw/images.rs
crates/kas-wgpu/src/draw/text_pipe.rs
crates/kas-widgets/src/label.rs
crates/kas-widgets/src/text.rs

Ctrl+Q was already mapped to `Command::Exit`; this is now handled.
Similarly, Alt+F4 maps to `Command::Close` which is now handled: close the popup or window if none.
Also added `AppData::suspended` to allow data saving on suspend/exit.

Better handling for close/suspend/exit

---

crates/kas-macros/src/lib.rs
crates/kas-macros/src/make_layout.rs
crates/kas-macros/src/widget.rs
crates/kas-macros/src/widget_args.rs
crates/kas-widgets/src/combobox.rs
examples/gallery.rs

Previously, widgets embedded in input data could support input data. This was rarely ever used within custom widgets but commonly used as part of "widget constructor macros" like `column!`, until #476 made those return named widgets (like `Column`).
We can now remove this feature. Motivation (aside from some simpler code) is that this avoids some confusing errors. For example, the last commit here simply in-lines a widget field which is never accessed nor uses input data:
```diff
diff --git a/crates/kas-widgets/src/combobox.rs b/crates/kas-widgets/src/combobox.rs
index b7a2f49d..c8074527 100644
--- a/crates/kas-widgets/src/combobox.rs
+++ b/crates/kas-widgets/src/combobox.rs
@@ -29,7 +29,7 @@ impl_scope! {
/// when selected. If a handler is specified via [`Self::with`] or
/// …
```

Remove input data from widget layout syntax items

---

.github/workflows/test.yml
Cargo.lock.msrv
Cargo.toml
crates/kas-core/Cargo.toml
crates/kas-core/src/config/theme.rs
crates/kas-core/src/core/widget_id.rs
crates/kas-core/src/event/cx/cx_pub.rs
crates/kas-core/src/messages.rs
crates/kas-core/src/runner/window.rs
crates/kas-resvg/Cargo.toml
crates/kas-view/src/list_view.rs
crates/kas-view/src/matrix_view.rs
src/lib.rs

Trait upcasting allows the pre-formatted part of `Erased` messages to be removed.
I also investigated removing `fn Tile::as_tile(&self) -> &dyn Tile`. This almost worked:
- `fn TileExt::find_widget` is implemented for all `T: Tile` and must be able to convert `&self` to `&dyn Tile`; it appears we need `T: std::marker::Unsize<dyn Tile>` (unstable) to make this work
- While some usages of `w.as_tile()` could be replaced with just `&w` (or just `w`), some required `w as &dyn Tile` or similar for unclear reasons; overall code looks worse as a result

Update MSRV to 1.86 for dyn trait upcast; update deps

---

crates/kas-core/src/core/collection.rs
crates/kas-core/src/core/impls.rs
crates/kas-core/src/core/node.rs
crates/kas-core/src/core/tile.rs
crates/kas-core/src/core/widget.rs
crates/kas-macros/src/collection.rs
crates/kas-macros/src/widget.rs
crates/kas-macros/src/widget_derive.rs
crates/kas-view/src/list_view.rs
crates/kas-view/src/matrix_view.rs
crates/kas-widgets/src/adapt/adapt_events.rs
crates/kas-widgets/src/float.rs
crates/kas-widgets/src/grid.rs
crates/kas-widgets/src/list.rs
crates/kas-widgets/src/menu/menubar.rs
crates/kas-widgets/src/menu/submenu.rs
crates/kas-widgets/src/splitter.rs
crates/kas-widgets/src/stack.rs

Motivation:
- Simpler fn signatures
- Reduces stack depth of an example `panic!()` placed in `Spinner::handle_event` tested in the gallery from 155 items to 99.
This locks in some of the changes from #487 since prior to that `fn ListView::child_node` would not pass the borrow checker (unable to return borrow of temporary data item).

Replace fns for_child* with get_child* to reduce stack depth

---

crates/kas-core/src/event/cx/mod.rs
crates/kas-core/src/event/cx/platform.rs
crates/kas-core/src/event/cx/press.rs
crates/kas-core/src/event/cx/press/mouse.rs
crates/kas-core/src/event/cx/press/touch.rs
crates/kas-core/src/geom/vector.rs
crates/kas-core/src/runner/window.rs
crates/kas-core/src/theme/draw.rs
crates/kas-core/src/theme/simple_theme.rs
crates/kas-macros/src/extends.rs

Revised from #491: update need-frame-update which now appears to have fixed all freezes during pan operations (i.e click+drag).
Copied from #491: add click-click-drag gesture, used to enable scale and rotate "panning" by mouse: click to set a fixed point, then click+drag to move a second point. Draw a marker for the fixed point. This only applies to panning operations supporting scaling and/or rotation (test with `examples/mandlebrot`).

Fix freezes during pan events, add click-click-drag gesture

---

crates/kas-core/src/config/config.rs
crates/kas-core/src/config/event.rs
crates/kas-core/src/event/components.rs
crates/kas-core/src/event/cx/mod.rs
crates/kas-core/src/event/cx/platform.rs
crates/kas-core/src/event/cx/press.rs
crates/kas-core/src/event/cx/press/mouse.rs
crates/kas-core/src/event/cx/press/touch.rs
crates/kas-core/src/event/cx/press/velocity.rs
crates/kas-core/src/event/events.rs
crates/kas-core/src/event/response.rs
crates/kas-core/src/geom/vector.rs
crates/kas-core/src/messages.rs
crates/kas-core/src/runner/event_loop.rs
crates/kas-core/src/runner/window.rs
crates/kas-view/src/list_view.rs
crates/kas-view/src/matrix_view.rs
crates/kas-widgets/src/combobox.rs
crates/kas-widgets/src/edit.rs
crates/kas-widgets/src/event_config.rs
crates/kas-widgets/src/scroll.rs
crates/kas-widgets/src/scroll_label.rs
crates/kas-widgets/src/scroll_text.rs
crates/kas-widgets/src/spinner.rs
examples/gallery.rs

Mouse cursor and touch velocity is now always sampled and available through `fn EventState::press_velocity`.
"Glide scrolling" is rebranded under the more common name "kinetic scrolling" and significantly improved.

Revise kinetic scrolling

---

Cargo.toml
crates/kas-core/src/config/font.rs
crates/kas-core/src/text/mod.rs
crates/kas-core/src/theme/text.rs
crates/kas-wgpu/Cargo.toml
crates/kas-wgpu/src/draw/text_pipe.rs

Support using [Swash](https://github.com/dfrg/swash) for glyph rastering as an alternative over `ab_glyph` or `fontique`.
Selectively import some parts of `kas_text` into `kas::text`, hiding parts which are not of interest to `kas_core` or widgets. `kas_wgpu` thus requires some direct imports from `kas_text`.
Migrate `kas_text::raster` code into `kas_wgpu`. See also https://github.com/kas-gui/kas-text/pull/91.

Support Swash glyph rastering; restrict kas::text re-exports

---

Cargo.toml
crates/kas-core/src/config/config.rs
crates/kas-core/src/config/font.rs
crates/kas-core/src/theme/dimensions.rs
crates/kas-core/src/theme/flat_theme.rs
crates/kas-core/src/theme/simple_theme.rs
crates/kas-core/src/theme/size.rs
crates/kas-core/src/theme/text.rs
crates/kas-core/src/theme/traits.rs
crates/kas-wgpu/src/shaded_theme.rs
crates/kas-widgets/src/edit.rs
crates/kas-widgets/src/scroll_label.rs
crates/kas-widgets/src/scroll_text.rs
examples/calculator.rs
examples/clock.rs
examples/gallery.rs

Updates kas-text for https://github.com/kas-gui/kas-text/pull/94
This implements font resolution by script, thus many more characters resolve to a valid glyph, though not all.
Some functionality is lost here:
- Read/write support for font configuration: the selector changed, is non-trivial to convert due to usage of a lookup table. TODO for later.
- `SizeCx::line_height` was removed since this depends on the font, which now depends on the text script. Instead we specify `EditField` height in `Em`s (or actual text height, whichever is greater).

Update kas-text: use Fontique + Swash

---

crates/kas-core/src/config/config.rs
crates/kas-core/src/config/event.rs
crates/kas-core/src/config/shortcuts.rs
crates/kas-core/src/core/widget_id.rs
crates/kas-core/src/draw/draw.rs
crates/kas-core/src/theme/draw.rs
crates/kas-wgpu/src/draw/draw_pipe.rs
crates/kas-wgpu/src/draw/images.rs
crates/kas-wgpu/src/draw/mod.rs
crates/kas-wgpu/src/draw/text_pipe.rs
crates/kas-wgpu/src/options.rs
crates/kas-widgets/src/menu/menu_entry.rs
crates/kas-widgets/src/menu/mod.rs
crates/kas-widgets/src/menu/submenu.rs
src/runner.rs

This should support drawing colour emojis, except that the font system (kas-text + fontique) always finds a simple outline first.
Possibly the best way to fix that is to via [this](https://github.com/linebender/parley/issues/371#issuecomment-2934501589) (i.e. modify `fontique::Query` to limit results to those supporting the matching `Block` or unicode range).

Support drawing RGBA glyphs

---

crates/kas-core/src/core/widget.rs
crates/kas-macros/src/lib.rs
crates/kas-macros/src/widget.rs
crates/kas-macros/src/widget_args.rs
crates/kas-widgets/src/adapt/with_label.rs
crates/kas-widgets/src/filler.rs
crates/kas-widgets/src/float.rs
crates/kas-widgets/src/frame.rs
crates/kas-widgets/src/grid.rs
crates/kas-widgets/src/image.rs
crates/kas-widgets/src/list.rs
crates/kas-widgets/src/mark.rs
crates/kas-widgets/src/scroll.rs
crates/kas-widgets/src/scroll_bar.rs
crates/kas-widgets/src/separator.rs

New `#[collection]` attribute to replace explicit `num_children` / `get_child` / `child_node` definitions on a few widgets.
Drop support for `type Data = ...` in `#[widget]` attr args; instead:
- Assume `Data = ()` without `impl Events { ... }`, `impl Widget { ... }` or children
- Assume `Data = <#field_ty as ::kas::Collection>::Data` without `impl Events { ... }`, `impl Widget { ... }` or children but with `#[collection]` attribute on some field
- Require explicit definition (on `Events` or `Widget`) otherwise

#[widget] macro revisions

---

Cargo.toml
crates/kas-core/Cargo.toml
crates/kas-core/src/accesskit.rs
crates/kas-core/src/core/role.rs
crates/kas-core/src/core/tile.rs
crates/kas-core/src/core/widget_id.rs
crates/kas-core/src/dir.rs
crates/kas-core/src/event/cx/cx_pub.rs
crates/kas-core/src/event/cx/mod.rs
crates/kas-core/src/event/cx/platform.rs
crates/kas-core/src/event/cx/press/touch.rs
crates/kas-core/src/geom.rs
crates/kas-core/src/lib.rs
crates/kas-core/src/messages.rs
crates/kas-core/src/popup.rs
crates/kas-core/src/root.rs
crates/kas-core/src/runner/event_loop.rs
crates/kas-core/src/runner/mod.rs
crates/kas-core/src/runner/runner.rs
crates/kas-core/src/runner/shared.rs
crates/kas-core/src/runner/window.rs
crates/kas-widgets/src/combobox.rs
crates/kas-widgets/src/edit.rs
crates/kas-widgets/src/label.rs
crates/kas-widgets/src/menu/submenu.rs
crates/kas-widgets/src/scroll_label.rs
crates/kas-widgets/src/slider.rs
crates/kas-widgets/src/spin_box.rs

Replaces #512. In comparison:
- Widget code does not use AccessKit as an API; instead #519 added `fn Tile::role()`. This will doubtless need some additions, but lets widgets report necessary details without dependency on AccessKit (and with a nicer API in my opinion).
- Output to AccessKit should be largely the same as #512.
- Some more actions are supported vs #512.
This PR still needs a few tweaks (TEMP / TODO commits) but is testable.
@DataTriny I'd appreciate if you gave this a little test and some feedback. I have successfully tested with a screen reader. Any obvious issues? My notes:
- I didn't use `accesskit::Role::GenericContainer` at all here; just `Unknown` for layout containers. Is that acceptable?
- I notice some focus tracking issues in Kas when using access keys. Edit: cause …

AccessKit integration (mark 2)

---

crates/kas-core/src/core/impls.rs
crates/kas-core/src/core/node.rs
crates/kas-core/src/core/role.rs
crates/kas-core/src/core/tile.rs
crates/kas-core/src/core/widget.rs
crates/kas-core/src/event/cx/cx_pub.rs
crates/kas-core/src/text/string.rs
crates/kas-widgets/src/adapt/with_label.rs
crates/kas-widgets/src/button.rs
crates/kas-widgets/src/check_box.rs
crates/kas-widgets/src/combobox.rs
crates/kas-widgets/src/edit.rs
crates/kas-widgets/src/label.rs
crates/kas-widgets/src/menu/menu_entry.rs
crates/kas-widgets/src/menu/mod.rs
crates/kas-widgets/src/menu/submenu.rs
crates/kas-widgets/src/nav_frame.rs
crates/kas-widgets/src/radio_box.rs
crates/kas-widgets/src/slider.rs
crates/kas-widgets/src/tab_stack.rs
examples/mandlebrot/mandlebrot.rs

Fix #522 by allowing the parent to register itself or another child as handler of an `AccessLabel`'s `access_key`.
Let navigable widgets advertise support for `accesskit::Action::Focus` by replacing `const Events::NAVIGABLE` with `fn Tile::navigable`. This is a further change to a recent change (`Events::NAVIGABLE`), and justifiable since (a) "is navigable" is a property, not event handling; and (b) `const` members are not accessible from dyn-safe traits.

Fix #522; move Events::NAVIGABLE to Tile::navigable

---

crates/kas-core/src/event/components.rs
crates/kas-core/src/event/response.rs
crates/kas-core/src/geom.rs
crates/kas-view/src/grid_view.rs
crates/kas-view/src/list_view.rs
crates/kas-wgpu/src/draw/draw_pipe.rs
examples/reformat-id.rs

Some changes to `ListView` and `GridView`:
- Rename `update_widgets` to `map_view_widgets` and avoid calling (or exit early) if not necessary; this improves performance when scrolling with many child widgets (e.g. `times-tables` with ~2800 visible entries now has usable performance in debug builds and very good performance in release builds).
- Resize view widgets automatically when required. This fixes the overlapping text when longer `times-tables` entries are scrolled into view.
- Use a virtual scroll offset to avoid positioning view widgets far from the origin. This increases the scrollable range, e.g. in `data-list-view` from ~500'000 to ~26'000'000. The main motivation for this was just to prove that this is possible.
Also, `examples/reformat-id.rs` now supports `#` encoded widget …

List/GridView improvements: scrolling, sizing, performance

---

crates/kas-core/src/draw/mod.rs
crates/kas-core/src/runner/window.rs
examples/data-list-view.rs
examples/hello.rs

Avoid continuous redraws with timed animation (e.g. a flashing text cursor). Previously timed animation requests where handled the same way as continuous animation requests.
Update `hello` example to use a declarative UI description instead of just a message box.

hello example, timed animation

---

crates/kas-core/src/event/cx/press.rs
crates/kas-core/src/event/cx/press/mouse.rs

This should avoid calling `winit::window::Window::set_cursor` redundantly.

Revise mouse-cursor icon setting

---

crates/kas-core/src/accesskit.rs
crates/kas-core/src/event/cx/accessibility.rs
crates/kas-core/src/event/cx/mod.rs
crates/kas-core/src/event/cx/press/mouse.rs
crates/kas-core/src/event/cx/window.rs
crates/kas-core/src/runner/common.rs
crates/kas-core/src/runner/event_loop.rs
crates/kas-core/src/runner/mod.rs
crates/kas-core/src/runner/runner.rs
crates/kas-core/src/runner/shared.rs
crates/kas-core/src/runner/window.rs
crates/kas-core/src/window/window.rs
crates/kas-widgets/src/dialog.rs
examples/text-editor/text-editor.rs
src/runner.rs

Various non-API-breaking revisions to runner (window and shared state) code. `enum Pending` drops two generic parameters. `runner::Window` could theoretically be instantiated for multiple input data types now, though I opted not to do so.
Add fn `EventCx::add_dataless_window`: this is like `add_window` except does not require the user to provide the input data type (and does not allow the new window to access said data). Note that this is a workaround since adding the runner input data type to `EventCx` as a generic parameter would be enormously disruptive.
Add fn `Window::set_modal_with_parent`. This uses [`with_owner_window`](https://docs.rs/winit/latest/winit/platform/windows/trait.WindowAttributesExtWindows.html#tymethod.with_owner_window) and `with_skip_taskbar` on Windows but is …

Revise window / shared-runner-state code; add fns add_dataless_window and set_modal_with_parent

---

crates/kas-core/src/core/events.rs
crates/kas-core/src/core/layout.rs
crates/kas-core/src/window/window.rs
crates/kas-macros/src/widget.rs
crates/kas-view/src/grid_view.rs
crates/kas-view/src/list_view.rs
crates/kas-widgets/src/adapt/with_label.rs
crates/kas-widgets/src/button.rs
crates/kas-widgets/src/check_box.rs
crates/kas-widgets/src/combobox.rs
crates/kas-widgets/src/edit.rs
crates/kas-widgets/src/float.rs
crates/kas-widgets/src/grid.rs
crates/kas-widgets/src/list.rs
crates/kas-widgets/src/menu/menu_entry.rs
crates/kas-widgets/src/menu/menubar.rs
crates/kas-widgets/src/menu/submenu.rs
crates/kas-widgets/src/radio_box.rs
crates/kas-widgets/src/scroll.rs
crates/kas-widgets/src/scroll_bar.rs
crates/kas-widgets/src/scroll_label.rs
crates/kas-widgets/src/slider.rs
crates/kas-widgets/src/spin_box.rs
crates/kas-widgets/src/splitter.rs
crates/kas-widgets/src/stack.rs
crates/kas-widgets/src/tab_stack.rs
examples/cursors.rs

This revises #563: `fn probe` is moved to trait `Events`.
After #563, rust-analyzer complains: `fn probe` is not a member of trait `Layout`.
It doesn't do this concerning `type Data` within trait `Events` (this might be a bug).
Further, I'd prefer not having the method in trait `Tile` (it should not be called, therefore should not be accessible from `dyn Widget`) or a new trait (purely to reduce the number of items in crate `kas`). `Events` works fine however.

Move fn probe to trait Events

---

crates/kas-core/src/core/events.rs
crates/kas-core/src/core/layout.rs
crates/kas-core/src/core/tile.rs
crates/kas-core/src/core/widget.rs
crates/kas-core/src/event/cx/press/mouse.rs
crates/kas-core/src/event/cx/send.rs
crates/kas-core/src/event/event.rs
crates/kas-core/src/event/mod.rs
crates/kas-macros/src/make_layout.rs
crates/kas-macros/src/widget.rs
crates/kas-macros/src/widget_derive.rs
crates/kas-widgets/src/dialog.rs
crates/kas-widgets/src/menu/mod.rs

Allow selection of the message in dialog boxes.
Move `fn try_probe` from trait `Layout` to `Tile` since non-widget implementations cannot implement `try_probe`. This fixes a bug where the generated `try_probe` would return `None` in widgets like `Label` and `SelectableText` where layout is generated over a non-widget.

Move `fn try_probe` and allow selection of message in dialog boxes

---

crates/kas-core/src/core/events.rs
crates/kas-core/src/core/layout.rs
crates/kas-core/src/core/tile.rs
crates/kas-core/src/core/widget.rs
crates/kas-core/src/event/config_cx.rs
crates/kas-core/src/event/cx/mod.rs
crates/kas-macros/src/widget.rs
crates/kas-view/src/data_clerk.rs
crates/kas-view/src/generator.rs
crates/kas-view/src/grid_view.rs
crates/kas-view/src/list_view.rs

- Update documentation on widget lifecycle
- Configuring a widget with invalid `Id` is an error, not something to silently ignore
- Call `Events::update` after `configure_recurse`
- Add `DataClerk::mock_item` for explicit control over sizing before data is available
- Tweak `ListView` and `GridView` configuration & sizing

Widget lifecycle: configure_recurse before events; mock view item for sizing

---

crates/kas-core/src/core/events.rs
crates/kas-macros/src/widget.rs
crates/kas-view/src/grid_view.rs
crates/kas-view/src/list_view.rs
crates/kas-widgets/src/list.rs

This reverts the configure/update order change of #573 since it could allow children to be updated before their parent. The goal of that change was to ensure that children are configured before the parent is updated which *could* be supported with two separate tree traversals (configure, update), but in practice parent-update-before-child-configure seems to work fine.
More tweaks to ListView/GridView configuration included. Changing data length can no longer cause a resize since (a) the view is scrollable and (b) in most cases, making this useful would require resizing the window, but allowing widgets to resize the window could result in undesirable (and slow) behaviour.
Add `fn truncate` to the `List` widget.

Call `update` before `configure_recurse`; tweak view controllers
