- kas-macros/src/layout.rs
- kas-wgpu/examples/dynamic.rs
- kas-wgpu/examples/theme.rs
- kas-wgpu/src/theme.rs
- kas-wgpu/src/window.rs
- src/event/handler.rs
- src/geom.rs
- src/layout/mod.rs
- src/layout/row_solver.rs
- src/lib.rs
- src/theme.rs
- src/toolkit.rs
- src/traits.rs
- src/widget/dynamic.rs
- src/widget/list.rs
- src/widget/mod.rs
- src/widget/scroll.rs
Optimise drawing & event handling of `DynVec` from `O(n)` to `O(log n)`; also cull draw operations on other hidden child widgets sooner.
> Optimisations

- Cargo.toml
- README.md
- kas-wgpu/Cargo.toml
- kas-wgpu/src/event_loop.rs
- kas-wgpu/src/lib.rs
- kas-wgpu/src/window.rs
- src/event/manager.rs
- src/geom.rs
Blocker: https://github.com/rust-windowing/winit/pull/1408/
> Update winit to 0.20.0

- CHANGELOG.md
- Cargo.toml
- kas-macros/Cargo.toml
- kas-wgpu/Cargo.toml
Update changelog and version numbers
> Prepare 0.2.0 release

- kas-macros/src/args.rs
- kas-macros/src/layout.rs
- kas-macros/src/lib.rs
- kas-wgpu/examples/dynamic.rs
- kas-wgpu/examples/gallery.rs
- kas-wgpu/src/theme.rs
- src/data.rs
- src/event/handler.rs
- src/geom.rs
- src/layout/grid_solver.rs
- src/layout/misc_solver.rs
- src/layout/mod.rs
- src/layout/row_solver.rs
- src/layout/single_solver.rs
- src/layout/size_rules.rs
- src/layout/sizer.rs
- src/macros.rs
- src/theme.rs
- src/traits.rs
- src/widget/button.rs
- src/widget/checkbox.rs
- src/widget/filler.rs
- src/widget/list.rs
- src/widget/mod.rs
- src/widget/radiobox.rs
- src/widget/scroll.rs
- src/widget/scrollbar.rs
- src/widget/text.rs
- Rename trait `Direction` → `Directional` and struct `DynDirection` → enum `Direction` and move to `kas::data`
- Add `StretchPolicy` enum; add to `SizeRules` struct and use when target size > ideal
- Tweak widget sizing & remove draw hack for checkbox
- New `Filler` widget
- Some fixes for `ScrollRegion`
- Add `TextClass::EditMulti` variant
- Add optional widget alignment, configurable from widgets and from `#[widget]` attribute
> Layout adjustments

- .travis.yml
- README.md
- kas-theme/Cargo.toml
- kas-theme/README.md
- kas-wgpu/Cargo.toml
- kas-wgpu/README.md
> Move font-kit dependency to kas-theme and fix Travis

- Cargo.toml
- kas-theme/src/flat_theme.rs
- kas-theme/src/shaded_theme.rs
- kas-wgpu/Cargo.toml
- kas-wgpu/examples/gallery.rs
- kas-wgpu/examples/mandlebrot.rs
- src/data.rs
- src/event/enums.rs
- src/event/events.rs
- src/event/manager.rs
- src/event/mod.rs
- src/lib.rs
- src/traits.rs
- src/widget/slider.rs
Support key navigation for sliders: inclusion in <Tab> navigation, highlighting, ability to respond to Up, Home, PageDown, etc.
Also support reversed key navigation with Shift+Tab.
> Key navigation support for sliders

- README.md
- kas-wgpu/examples/README.md
- kas-wgpu/examples/gallery.rs
- src/event/events.rs
- src/event/manager.rs
- src/event/manager/mgr_pub.rs
- src/event/manager/mgr_tk.rs
- src/widget/combobox.rs
- src/widget/list.rs
- src/widget/menu/menubar.rs
- src/widget/menu/submenu.rs
Let SubMenu, ComboBox and MenuBar handle some NavKey events for menu navigation. Also:
-   a more robust way of closing other popups: NewPopup event
-   updates to READMEs
> Add arrow-based navigation for menus

- CONTRIBUTING.md
- kas-wgpu/examples/stopwatch.rs
- src/lib.rs
- src/traits/widget.rs
- src/widget/combobox.rs
- src/widget/editbox.rs
- add `WidgetCore::with_disabled`
- extend `ComboBox` API (adding & removing entries, programmatic selection)
- call `EditGuard::edit` initially and on programmatic changes
- add `CONTRIBUTING` document
> Misc. changes

- Cargo.toml
- kas-theme/src/dim.rs
- kas-theme/src/flat_theme.rs
- kas-theme/src/shaded_theme.rs
- kas-wgpu/Cargo.toml
- kas-wgpu/examples/markdown.rs
- kas-wgpu/src/draw/draw_pipe.rs
- src/widget/label.rs
See https://github.com/kas-gui/kas-text/pull/29
> Update kas-text: simple markdown parser

- CONTRIBUTING.md
- kas-theme/src/flat_theme.rs
- kas-theme/src/multi.rs
- kas-theme/src/shaded_theme.rs
- kas-theme/src/theme_dst.rs
- kas-theme/src/traits.rs
- kas-wgpu/examples/custom-theme.rs
- kas-wgpu/examples/dynamic.rs
- kas-wgpu/examples/gallery.rs
- kas-wgpu/examples/mandlebrot.rs
- kas-wgpu/src/window.rs
- src/draw/colour.rs
- src/layout/size_rules.rs
- src/widget/filler.rs
Expection: Colour type which will be replaced later
> Spelling reform: use US-English in API

- .github/workflows/test.yml
- kas-macros/src/lib.rs
- kas-wgpu/examples/filter-list.rs
- kas-wgpu/src/draw/custom.rs
- src/event/manager.rs
- src/event/manager/mgr_pub.rs
- src/event/manager/mgr_shell.rs
- src/layout/sizer.rs
- src/traits/impls.rs
- src/traits/widget.rs
- src/widget/combobox.rs
- src/widget/list.rs
- src/widget/menu.rs
- src/widget/menu/menubar.rs
- src/widget/splitter.rs
- src/widget/stack.rs
- src/widget/view/filter.rs
- src/widget/view/list.rs
- src/widget/view/mod.rs
- src/widget/view/shared.rs
- src/widget/window.rs
Perhaps it's surprising that it took this long to have `widget.len()` accidentally compile and do the wrong thing...
> Add Filter trait; give WidgetChildren methods more unique names

- .github/workflows/test.yml
- CHANGELOG.md
- Cargo.toml
Backport a patch from master to fix the calculator example.
> Prepare 0.7.1

- .github/workflows/test.yml
- Cargo.toml
- README.md
- kas-wgpu/Cargo.toml
- kas-wgpu/README.md
- kas-wgpu/src/draw/text_pipe.rs
- kas-wgpu/src/window.rs
See https://github.com/kas-gui/kas-text/pull/50
> Move font raster out to kas-text

- kas-macros/src/lib.rs
- kas-theme/src/config.rs
- kas-wgpu/src/draw/text_pipe.rs
- src/adapter/map.rs
- src/adapter/reserve.rs
- src/layout/size_rules.rs
- src/widget/button.rs
- src/widget/checkbox.rs
- src/widget/combobox.rs
- src/widget/menu/menu_entry.rs
- src/widget/mod.rs
- src/widget/radiobox.rs
- src/widget/view/single_view.rs
- src/widget/window.rs
Generic `Button` widget, use `DebugStruct`, use 10pt font by default, better underline separation
> Button widget, use debug_struct

- .github/workflows/build.yml
- kas-wgpu/examples/gallery.rs
This builds three examples on every PR merge (hopefully).
Also changes the label in the gallery to showcase multilingual script support (or not, depending on font discovery).
> Builder action

- crates/kas-resvg/Cargo.toml
- crates/kas-resvg/src/svg.rs
- crates/kas-widgets/Cargo.toml
- crates/kas-widgets/src/menu/menubar.rs
Fixes #251. Update `resvg` to latest version.
> Update resvg; fix slow-to-open menus

- README.md
- ROADMAP.md
- crates/kas-core/src/draw/images.rs
- crates/kas-core/src/theme/draw.rs
- crates/kas-core/src/toolkit.rs
- crates/kas-resvg/src/canvas.rs
- crates/kas-resvg/src/lib.rs
- crates/kas-wgpu/src/draw/custom.rs
- crates/kas-wgpu/src/lib.rs
- crates/kas-wgpu/src/options.rs
- crates/kas-wgpu/src/shared.rs
- crates/kas-wgpu/src/window.rs
- examples/canvas.rs
- examples/clock.rs
- src/lib.rs
The `canvas` example is now animated, which turned out to be a bad idea since it uses slow CPU rendering. Anyway, it's valid proof-of-concept and the `clock` example can be tweaked to prove the need for an FPS-limiter.
> TkAction::ANIMATE and KAS_FPS_LIMIT

- crates/kas-core/src/layout/size_rules.rs
> SizeRules::solve_seq_total: fix to avoid negative widths

- crates/kas-widgets/src/menu/menubar.rs
- crates/kas-widgets/src/menu/submenu.rs
> Fix MenuBar behaviour

- crates/kas-core/src/core/widget.rs
- crates/kas-core/src/event/components.rs
- crates/kas-core/src/event/events.rs
- crates/kas-core/src/event/handler.rs
- crates/kas-core/src/event/manager.rs
- crates/kas-core/src/event/manager/mgr_pub.rs
- crates/kas-core/src/event/response.rs
- crates/kas-core/src/prelude.rs
- crates/kas-macros/src/widget.rs
- crates/kas-widgets/src/button.rs
- crates/kas-widgets/src/checkbox.rs
- crates/kas-widgets/src/combobox.rs
- crates/kas-widgets/src/edit_field.rs
- crates/kas-widgets/src/menu/submenu.rs
- crates/kas-widgets/src/radiobox.rs
- crates/kas-widgets/src/scroll.rs
- crates/kas-widgets/src/scrollbar.rs
- crates/kas-widgets/src/view/list_view.rs
- crates/kas-widgets/src/view/matrix_view.rs
> Bug fixes; Event::activate_on_press

- crates/kas-core/Cargo.toml
- crates/kas-wgpu/Cargo.toml
- crates/kas-widgets/src/check_box.rs
- crates/kas-widgets/src/edit_field.rs
- crates/kas-widgets/src/radio_box.rs
- crates/kas-widgets/src/scroll_label.rs
- examples/data-list-view.rs
- examples/data-list.rs
Corresponding PR: https://github.com/kas-gui/kas-text/pull/69
> Update KAS-text; shrink clickable area of check/radio button; RadioButton::select

- crates/kas-core/src/layout/mod.rs
- crates/kas-core/src/layout/size_rules.rs
- crates/kas-core/src/layout/size_types.rs
- crates/kas-core/src/layout/visitor.rs
- crates/kas-core/src/theme/draw.rs
- crates/kas-core/src/theme/mod.rs
- crates/kas-core/src/theme/size.rs
- crates/kas-core/src/theme/style.rs
- crates/kas-macros/src/lib.rs
- crates/kas-macros/src/make_layout.rs
- crates/kas-theme/src/dim.rs
- crates/kas-theme/src/flat_theme.rs
- crates/kas-theme/src/shaded_theme.rs
- crates/kas-theme/src/simple_theme.rs
- crates/kas-view/src/list_view.rs
- crates/kas-view/src/matrix_view.rs
- crates/kas-widgets/src/edit.rs
- crates/kas-widgets/src/menu/menubar.rs
- crates/kas-widgets/src/menu/submenu.rs
- crates/kas-widgets/src/scroll.rs
- crates/kas-widgets/src/spinner.rs
- examples/gallery.rs
> New FrameRules model; adjust margins

- crates/kas-core/src/draw/draw.rs
- crates/kas-core/src/root.rs
- crates/kas-core/src/theme/draw.rs
Fixes bugs with pop-up menus inside scrolled regions
> Pop-ups use ancestors' coordinate translations

- crates/kas-core/src/event/components.rs
- crates/kas-core/src/theme/config.rs
- crates/kas-core/src/theme/draw.rs
- crates/kas-core/src/theme/simple_theme.rs
- crates/kas-core/src/theme/style.rs
- crates/kas-macros/src/extends.rs
- crates/kas-view/src/lib.rs
- crates/kas-view/src/list_view.rs
- crates/kas-view/src/matrix_view.rs
- Allow accelerating momentum scrolling when already moving
- Better momentum scrolling / selection interaction
- Selection in List/MatrixView now (optionally) uses background-highlighting instead of a box
> Improve momentum scrolling, selection highlight

- CHANGELOG.md
- Cargo.toml
- ROADMAP.md
- crates/kas-core/Cargo.toml
- crates/kas-core/src/core/node.rs
- crates/kas-dylib/Cargo.toml
- crates/kas-macros/Cargo.toml
- crates/kas-resvg/Cargo.toml
- crates/kas-view/Cargo.toml
- crates/kas-wgpu/Cargo.toml
- crates/kas-widgets/Cargo.toml
- examples/mandlebrot/Cargo.toml
[CHANGELOG entry](https://github.com/kas-gui/kas/blob/443d0cef00c3f153926f5130830084c03596505b/CHANGELOG.md#0141--2023-12-12)
> Prepare 0.14.1

- Cargo.toml
- crates/kas-core/Cargo.toml
- crates/kas-resvg/Cargo.toml
- crates/kas-view/Cargo.toml
- crates/kas-wgpu/Cargo.toml
- crates/kas-widgets/Cargo.toml
- crates/kas-widgets/src/lib.rs
- crates/kas-widgets/src/text.rs
- examples/sync-counter.rs
- Fix doc build of kas-wgpu
- Make `kas::widgets::ImageError` public
> Doc fixes; pub ImageError

- crates/kas-macros/src/widget.rs
> Fix: allow calling fn rect() before assigning id

- crates/kas-core/src/core/layout.rs
- crates/kas-core/src/core/widget.rs
- crates/kas-core/src/root.rs
- crates/kas-macros/src/make_layout.rs
- crates/kas-macros/src/widget.rs
- crates/kas-view/src/list_view.rs
- crates/kas-view/src/matrix_view.rs
- crates/kas-widgets/src/adapt/with_label.rs
- crates/kas-widgets/src/check_box.rs
- crates/kas-widgets/src/edit.rs
- crates/kas-widgets/src/grid.rs
- crates/kas-widgets/src/list.rs
- crates/kas-widgets/src/menu/menu_entry.rs
- crates/kas-widgets/src/menu/menubar.rs
- crates/kas-widgets/src/menu/mod.rs
- crates/kas-widgets/src/menu/submenu.rs
- crates/kas-widgets/src/radio_box.rs
- crates/kas-widgets/src/scroll.rs
- crates/kas-widgets/src/scroll_bar.rs
- crates/kas-widgets/src/scroll_label.rs
- crates/kas-widgets/src/scroll_text.rs
- crates/kas-widgets/src/slider.rs
- crates/kas-widgets/src/spinner.rs
- crates/kas-widgets/src/splitter.rs
- crates/kas-widgets/src/stack.rs
- crates/kas-widgets/src/tab_stack.rs
- examples/cursors.rs
Also some reordering of impls.
> Move fn Events::probe to Tile with where Self: Sized clause

- crates/kas-core/src/core/tile.rs
- crates/kas-core/src/event/components.rs
- crates/kas-core/src/event/cx/cx_pub.rs
- crates/kas-core/src/event/cx/mod.rs
- crates/kas-core/src/event/cx/platform.rs
- crates/kas-core/src/event/events.rs
- crates/kas-core/src/event/mod.rs
- crates/kas-core/src/geom.rs
- crates/kas-core/src/root.rs
- crates/kas-core/src/runner/window.rs
- crates/kas-core/src/text/selection.rs
- crates/kas-widgets/src/edit.rs
- crates/kas-widgets/src/scroll_label.rs
- crates/kas-widgets/src/scroll_text.rs
This "seems" to work, with two big caveats:
- Font fallbacks are for now too limited to show all the glyphs
- It is not possible to notify the IME of surrounding / selected text (winit limitation)
> Input Method Editor (IME) support

- Cargo.toml
- crates/kas-core/src/config/font.rs
- crates/kas-core/src/runner/window.rs
- crates/kas-resvg/src/svg.rs
Uses https://github.com/kas-gui/kas-text/pull/93.
Also fix text scaling when scale factor changes.
> Update kas-text to use fontique; fix rescaling

- crates/kas-macros/src/widget.rs
- crates/kas-macros/src/widget_derive.rs
- crates/kas-widgets/src/check_box.rs
- crates/kas-widgets/src/filler.rs
- crates/kas-widgets/src/menu/submenu.rs
- crates/kas-widgets/src/radio_box.rs
- crates/kas-widgets/src/stack.rs
- examples/gallery.rs
- examples/mandlebrot/mandlebrot.rs
Standardise impl order of widget traits.
> impl Layout before Tile before Events before Widget

- CHANGELOG.md
- Cargo.toml
- crates/kas-core/Cargo.toml
- crates/kas-dylib/Cargo.toml
- crates/kas-macros/Cargo.toml
- crates/kas-resvg/Cargo.toml
- crates/kas-view/Cargo.toml
- crates/kas-wgpu/Cargo.toml
- crates/kas-widgets/Cargo.toml
- examples/mandlebrot/Cargo.toml
... with a ridiculously long change log.
> Prepare 0.16.0

- crates/kas-widgets/src/dialog.rs
- examples/text-editor/text-editor.rs
These new dialogs return a result to the creator on closure.
> Add dialog boxes: AlertUnsaved, AlertError; save support for text-editor

- .github/workflows/test.yml
- Cargo.toml
- crates/kas-core/Cargo.toml
- crates/kas-core/src/window/window.rs
- crates/kas-widgets/Cargo.toml
This drops the number of dependencies in default configuration significantly.
Also supports using "image" without all formats and adds flags for avif,jpeg,png,webp.
> Revise default feature sets

- crates/kas-core/src/event/cx/send.rs
- crates/kas-core/src/theme/text.rs
- crates/kas-view/src/driver.rs
- crates/kas-widgets/src/adapt/adapt_cx.rs
- crates/kas-widgets/src/stack.rs
- crates/kas-widgets/src/text.rs
- examples/data-list-view.rs
- examples/data-list.rs
> Mut text access, message sending doc
